// Command apigen generates the frontend's and the Android client's copy
// of the backend's HTTP API - wire types, enums, the model catalog, live
// topics, and the route table - from internal/httpapi (plus the packages
// it draws on), so the three can't silently drift apart.
//
// What it reads:
//
//   - Types: every package-level struct with a json-tagged field in
//     internal/httpapi and internal/live, and every named type those
//     reference. A lowercase-first Go name is capitalized and a trailing
//     "DTO"/"DTOOut" dropped (bookSummaryDTO -> BookSummary); Kotlin
//     appends "Dto".
//   - Enums: a named string type with constants in its own package becomes
//     a TS const array plus union (CHARACTER_VOICE_MODES/CharacterVoiceMode),
//     in declaration order; Kotlin keeps a String typealias plus an object
//     of constants, so a new server-side value never breaks decoding.
//   - The catalog (catalog.go): runtime values such as voices.CloneModels
//     and a few scalar constants, emitted as constants.
//   - Live topics (live.go): httpapi.registerLiveTopics' Register calls.
//   - Routes (routes.go): every mux.HandleFunc route, with its path/query
//     params, request body, response, and error codes worked out from the
//     handler's body.
//
// Struct tags override one field's client type: `tstype:"X"` (a TS type
// expression; any identifier in it that isn't generated must be declared
// by hand in frontend/src/api/types.ts, and is imported from there) and
// `kttype:"X"` (the Kotlin type, fully written out; such a field has no
// default, so it's required on the wire, unless it's nullable or a List,
// or the tag spells one out: `kttype:"Double = 0.0"`). A type whose doc
// comment contains "apigen:ts-hand" is left out of the TS output, for
// shapes TS can model more precisely by hand (e.g. discriminated unions).
// A handler whose doc contains "apigen:skip" isn't a route (the WebSocket).
//
// Kotlin fields default to Go's zero value, except omitempty/omitzero
// strings and numbers, which become nullable (defaulting to null): Go
// never sends a zero one, and Kotlin callers treat "absent" as "none"
// (`seriesIndex != null`, `durationSeconds?.let`). Omitted bools and
// lists stay non-null, since there absent really does mean false/empty.
// Types with a custom MarshalJSON are rejected unless every field using
// them carries both overrides, since their wire shape isn't derivable
// from their Go fields.
//
// Run via `go generate ./internal/httpapi` (or `make generate`);
// TestGeneratedUpToDate fails while the checked-in output is stale.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/types"
	"os"
	"path/filepath"

	"golang.org/x/tools/go/packages"
)

const (
	modPath     = "github.com/rhino1998/lectable/backend"
	httpapiPkg  = modPath + "/internal/httpapi"
	livePkg     = modPath + "/internal/live"
	voicesPkg   = modPath + "/internal/voices"
	emotionsPkg = modPath + "/internal/emotions"
	storePkg    = modPath + "/internal/store"

	tsOut       = "../frontend/src/api/generated.ts"
	ktRemoteDir = "../android/app/src/main/java/com/lectable/app/data/remote/"
	ktTypesOut  = ktRemoteDir + "dto/ApiTypes.kt"
	ktAPIOut    = ktRemoteDir + "LectableApi.kt"
	ktLiveOut   = ktRemoteDir + "LiveTopics.kt"

	ktDTOPackage    = "com.lectable.app.data.remote.dto"
	ktRemotePackage = "com.lectable.app.data.remote"

	headerNote = "Code generated by backend/cmd/apigen from backend/internal/httpapi. DO NOT EDIT."
)

func main() {
	dir := flag.String("dir", ".", "the backend module's root directory")
	check := flag.Bool("check", false, "exit non-zero if the checked-in output is stale instead of rewriting it")
	flag.Parse()
	outs, err := generate(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "apigen:", err)
		os.Exit(1)
	}
	stale := false
	for path, content := range outs {
		old, _ := os.ReadFile(path)
		if bytes.Equal(old, content) {
			continue
		}
		if *check {
			fmt.Fprintf(os.Stderr, "apigen: %s is stale; run `go generate ./internal/httpapi`\n", path)
			stale = true
			continue
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "apigen:", err)
			os.Exit(1)
		}
	}
	if stale {
		os.Exit(1)
	}
}

// generate loads the backend module rooted at dir and returns the
// generated files keyed by path (relative to dir).
func generate(dir string) (map[string][]byte, error) {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return nil, err
	}
	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedSyntax | packages.NeedTypesInfo | packages.NeedDeps | packages.NeedImports,
		Dir:  absDir,
	}, httpapiPkg, livePkg)
	if err != nil {
		return nil, err
	}
	if packages.PrintErrors(pkgs) > 0 {
		return nil, fmt.Errorf("failed to load %s", httpapiPkg)
	}
	g := newGen()
	packages.Visit(pkgs, nil, func(p *packages.Package) { g.index(p) })

	for _, path := range []string{httpapiPkg, livePkg} {
		scope := g.pkgs[path].Types.Scope()
		for _, name := range scope.Names() {
			tn, ok := scope.Lookup(name).(*types.TypeName)
			if !ok || tn.IsAlias() {
				continue
			}
			if st, ok := tn.Type().Underlying().(*types.Struct); ok && hasJSONField(st) {
				g.want(tn.Type().(*types.Named))
			}
		}
	}
	cat, err := g.catalog()
	if err != nil {
		return nil, err
	}
	topics, err := g.liveTopics()
	if err != nil {
		return nil, err
	}
	routes, err := g.routes()
	if err != nil {
		return nil, err
	}
	if err := g.drain(); err != nil {
		return nil, err
	}
	return map[string][]byte{
		filepath.Join(dir, tsOut):      g.renderTS(cat, topics, routes),
		filepath.Join(dir, ktTypesOut): g.renderKotlinTypes(cat),
		filepath.Join(dir, ktAPIOut):   g.renderKotlinAPI(routes),
		filepath.Join(dir, ktLiveOut):  g.renderKotlinLive(topics),
	}, nil
}
