// Package pronounce implements this app's pronunciation/normalization
// pass: unlike internal/deliverytags (strictly insert-only - a delivery
// tag never changes a paragraph's own words, enforced by
// deliverytags.ExtractInsertions rejecting anything else), fixing a
// mispronounced abbreviation genuinely needs to replace one span of text
// with a different spelling ("St." -> "Saint" or "Street", depending on
// context) so the TTS model actually says the right thing. That's a real
// exception to deliverytags' own "never reword real content" invariant,
// so it gets its own separate, more narrowly bounded mechanism rather
// than being folded into deliverytags itself.
//
// The safety story is different too, and simpler: a Substitution is never
// freely generated by an LLM the way a delivery pass's annotated text is
// (see internal/speakerattr's pronunciation.go). It's always one of a
// small, fixed set of candidate readings a regex found deterministically
// - the LLM only ever picks an index into that pre-computed list, never
// returns free text at all, so there's no diff-and-validate step needed
// here the way deliverytags.ExtractInsertions provides for tags: nothing
// this package's own callers do can ever hand Apply a substitution whose
// Replacement wasn't one of a hand-authored candidate list to begin with.
//
// Applied only when building a paragraph's generation-time text
// (Apply, used by store.Paragraph.ResolveGenerationText) - never to the
// reader's own on-screen text or to forced alignment's own reference
// text, both of which stay keyed to the paragraph's real, untouched
// content exactly as they already do for delivery tags.
package pronounce

import (
	"sort"
	"strings"

	"github.com/rhino1998/lectable/backend/internal/deliverytags"
)

// Substitution replaces a paragraph's own real text from Offset to
// Offset+Length (byte-indexed into that same paragraph's plain Text, the
// same coordinate space deliverytags.Insertion.Offset already uses) with
// Replacement.
type Substitution struct {
	Offset      int    `json:"offset"`
	Length      int    `json:"length"`
	Replacement string `json:"replacement"`
}

// Apply composes plain (a paragraph's own real, untouched text) with
// zero-width tag insertions (deliverytags.Insertion, from
// internal/speakerattr's delivery-tagging passes) and this package's own
// span-replacing Substitutions into one final generation-time string, in
// a single offset-ordered pass. Both kinds of edit are defined by an
// offset into that same original plain text, so composing them together
// in one pass - rather than applying substitutions first and then trying
// to re-target insertion offsets against the now-different-length result
// - keeps every offset meaningful throughout; this is what replaces
// deliverytags.Merge for a paragraph that has both kinds of edit (see
// store.Paragraph.ResolveGenerationText).
//
// An insertion and a substitution landing at the exact same offset writes
// the insertion first, matching "a tag colors what follows it" -
// including a substitution's own replacement text right after. Among
// insertions themselves (zero-width, so tied on both start and end), the
// stable sort preserves whatever relative order the caller's own slice
// already had them in - callers building that slice should append in the
// same category order deliverytags.Merge's own callers already do
// (Emotion-then-Style-then-Pacing, sentence-level before positional; see
// internal/speakerattr's own doc comments) to get the same stacking
// convention.
//
// An edit that overlaps one already applied (should never happen for
// insertions/substitutions each independently computed against
// non-overlapping spans, but not proven safe against every combination -
// e.g. two Substitutions from a stale/corrupt stored value) is silently
// skipped rather than corrupting the output, the same "a bad annotation
// is less harmful than blocking narration" treatment
// ResolveGenerationText already gives a tag that fails to re-extract.
func Apply(plain string, insertions []deliverytags.Insertion, subs []Substitution) string {
	type edit struct {
		start, end int
		text       string
	}
	edits := make([]edit, 0, len(insertions)+len(subs))
	for _, ins := range insertions {
		edits = append(edits, edit{start: ins.Offset, end: ins.Offset, text: ins.Tag})
	}
	for _, sub := range subs {
		edits = append(edits, edit{start: sub.Offset, end: sub.Offset + sub.Length, text: sub.Replacement})
	}
	sort.SliceStable(edits, func(i, j int) bool {
		if edits[i].start != edits[j].start {
			return edits[i].start < edits[j].start
		}
		// Zero-width insertions (end == start) sort before a substitution
		// starting at the same point (end > start) - see the doc comment
		// above.
		return edits[i].end < edits[j].end
	})

	var b strings.Builder
	pos := 0
	for _, e := range edits {
		if e.start < pos || e.end > len(plain) {
			continue
		}
		b.WriteString(plain[pos:e.start])
		b.WriteString(e.text)
		pos = e.end
	}
	b.WriteString(plain[pos:])
	return b.String()
}

// Compose merges a paragraph's pronunciation substitutions (pron) with its
// structural emphasis substitutions (emphasis - internal/epub's
// extractEmphasis: a span respelled in upper case and/or wrapped in
// quotes) into one non-overlapping list for Apply. The two routinely
// overlap - a bold stat line "Trait 2/3" is one emphasis span containing
// the "2/3" pronunciation fix - and Apply keeps only the first of two
// overlapping edits, which silently dropped the pronunciation fix. Here a
// pronunciation fix wholly inside an emphasis span is applied to that
// span's text first, then the span's own transform is re-applied to the
// result ("TRAIT TWO OF THREE"). A fix straddling a span's edge can't be
// nested, so the emphasis is dropped instead: saying the right word
// matters more than stressing it.
func Compose(plain string, pron, emphasis []Substitution) []Substitution {
	if len(emphasis) == 0 {
		return pron
	}
	out := make([]Substitution, 0, len(pron)+len(emphasis))
	nested := make([]bool, len(pron))
	for _, em := range emphasis {
		end := em.Offset + em.Length
		if em.Offset < 0 || end > len(plain) {
			continue
		}
		var inner []Substitution
		straddles := false
		for i, p := range pron {
			pEnd := p.Offset + p.Length
			switch {
			case pEnd <= em.Offset || p.Offset >= end:
				// disjoint
			case p.Offset >= em.Offset && pEnd <= end:
				inner = append(inner, Substitution{Offset: p.Offset - em.Offset, Length: p.Length, Replacement: p.Replacement})
				nested[i] = true
			default:
				straddles = true
			}
		}
		if straddles {
			continue
		}
		if len(inner) == 0 {
			out = append(out, em)
			continue
		}
		original := plain[em.Offset:end]
		out = append(out, Substitution{
			Offset:      em.Offset,
			Length:      em.Length,
			Replacement: reapplyEmphasis(original, em.Replacement, Apply(original, nil, inner)),
		})
	}
	for i, p := range pron {
		if !nested[i] {
			out = append(out, p)
		}
	}
	return out
}

// reapplyEmphasis applies to text whatever transform turned original into
// replacement - the upper-casing and/or quote-wrapping extractEmphasis
// produces.
func reapplyEmphasis(original, replacement, text string) string {
	quoted := len(replacement) == len(original)+2 && strings.HasPrefix(replacement, `"`) && strings.HasSuffix(replacement, `"`)
	body := replacement
	if quoted {
		body = replacement[1 : len(replacement)-1]
	}
	if body != original && body == strings.ToUpper(original) {
		text = strings.ToUpper(text)
	}
	if quoted {
		text = `"` + text + `"`
	}
	return text
}
