// Code generated by backend/cmd/apigen from backend/internal/httpapi. DO NOT EDIT.

@file:Suppress("unused")

package com.lectable.app.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * audioStatus is a generated clip's state on the wire - store's Audio*
 * values.
 *
 *
 * Values: see [AudioStatuses].
 */
typealias AudioStatus = String

/**
 * [AudioStatus]'s wire values, in declaration order.
 */
object AudioStatuses {
    const val PENDING: AudioStatus = "pending"
    const val GENERATING: AudioStatus = "generating"
    const val READY: AudioStatus = "ready"
    const val ERROR: AudioStatus = "error"
    val VALUES: List<AudioStatus> = listOf(PENDING, GENERATING, READY, ERROR)
}

/**
 * bulkAction is a Speakers-page whole-book action (POST
 * /api/books/{id}/bulk/{action}), in the page's display order. "generate"
 * queues the same "pipeline_generate_book" row as the library page's
 * Generate: All.
 *
 *
 * Values: see [BulkActions].
 */
typealias BulkAction = String

/**
 * [BulkAction]'s wire values, in declaration order.
 */
object BulkActions {
    const val ATTRIBUTION: BulkAction = "attribution"
    const val DESCRIPTION: BulkAction = "description"
    const val SCARE_QUOTE: BulkAction = "scare_quote"
    const val DIRECTION: BulkAction = "direction"
    const val PRONUNCIATION: BulkAction = "pronunciation"
    const val MUSIC_SCORING: BulkAction = "music_scoring"
    const val MUSIC_GENERATION: BulkAction = "music_generation"
    const val GENERATE: BulkAction = "generate"
    const val CHARACTERIZATION: BulkAction = "characterization"
    const val VOICES: BulkAction = "voices"
    val VALUES: List<BulkAction> = listOf(ATTRIBUTION, DESCRIPTION, SCARE_QUOTE, DIRECTION, PRONUNCIATION, MUSIC_SCORING, MUSIC_GENERATION, GENERATE, CHARACTERIZATION, VOICES)
}

/**
 * bulkScope is the ?scope= query param of POST .../bulk/{action}: "rest"
 * only touches items not done yet, "all" re-runs every one.
 *
 *
 * Values: see [BulkScopes].
 */
typealias BulkScope = String

/**
 * [BulkScope]'s wire values, in declaration order.
 */
object BulkScopes {
    const val REST: BulkScope = "rest"
    const val ALL: BulkScope = "all"
    val VALUES: List<BulkScope> = listOf(REST, ALL)
}

/**
 * CharacterVoiceMode is store.Book.CharacterVoiceMode's own type - one of
 * four mutually exclusive settings for whether/how a character's own
 * narration voice can override the book's:
 *
 *
 * Values: see [CharacterVoiceModes].
 */
typealias CharacterVoiceMode = String

/**
 * [CharacterVoiceMode]'s wire values, in declaration order.
 */
object CharacterVoiceModes {
    const val NARRATOR: CharacterVoiceMode = "narrator"
    const val ASSIGNED: CharacterVoiceMode = "assigned"
    const val INSTRUCT_UNASSIGNED: CharacterVoiceMode = "instruct_unassigned"
    const val INSTRUCT_ALL: CharacterVoiceMode = "instruct_all"
    val VALUES: List<CharacterVoiceMode> = listOf(NARRATOR, ASSIGNED, INSTRUCT_UNASSIGNED, INSTRUCT_ALL)
}

/**
 * errorCode is a machine-readable error reason a client can branch on
 * (errorResponse.Code).
 *
 *
 * Values: see [ErrorCodes].
 */
typealias ErrorCode = String

/**
 * [ErrorCode]'s wire values, in declaration order.
 */
object ErrorCodes {
    const val NO_SOURCE_EPUB: ErrorCode = "no_source_epub"
    const val TITLE_MISMATCH: ErrorCode = "title_mismatch"
    const val BOOK_EXISTS: ErrorCode = "book_exists"
    val VALUES: List<ErrorCode> = listOf(NO_SOURCE_EPUB, TITLE_MISMATCH, BOOK_EXISTS)
}

/**
 * exportFormat is an export file format on the wire - bookexport.Format.
 *
 *
 * Values: see [ExportFormats].
 */
typealias ExportFormat = String

/**
 * [ExportFormat]'s wire values, in declaration order.
 */
object ExportFormats {
    const val EPUB: ExportFormat = "epub"
    val VALUES: List<ExportFormat> = listOf(EPUB)
}

/**
 * jobTier is a job-queue priority tier on the wire - jobs.Tier*'s names,
 * most urgent first.
 *
 *
 * Values: see [JobTiers].
 */
typealias JobTier = String

/**
 * [JobTier]'s wire values, in declaration order.
 */
object JobTiers {
    const val URGENT: JobTier = "urgent"
    const val LOOKAHEAD: JobTier = "lookahead"
    const val NORMAL: JobTier = "normal"
    const val BACKGROUND: JobTier = "background"
    val VALUES: List<JobTier> = listOf(URGENT, LOOKAHEAD, NORMAL, BACKGROUND)
}

/**
 * resetPass is a pass the Speakers page can reset across a whole book
 * (POST /api/books/{id}/reset/{pass}) - every bulkAction except the
 * character-scoped ones.
 *
 *
 * Values: see [ResetPasses].
 */
typealias ResetPass = String

/**
 * [ResetPass]'s wire values, in declaration order.
 */
object ResetPasses {
    const val ATTRIBUTION: ResetPass = "attribution"
    const val DESCRIPTION: ResetPass = "description"
    const val SCARE_QUOTE: ResetPass = "scare_quote"
    const val DIRECTION: ResetPass = "direction"
    const val PRONUNCIATION: ResetPass = "pronunciation"
    const val MUSIC_SCORING: ResetPass = "music_scoring"
    const val MUSIC_GENERATION: ResetPass = "music_generation"
    const val GENERATE: ResetPass = "generate"
    val VALUES: List<ResetPass> = listOf(ATTRIBUTION, DESCRIPTION, SCARE_QUOTE, DIRECTION, PRONUNCIATION, MUSIC_SCORING, MUSIC_GENERATION, GENERATE)
}

/**
 * SFXEngine picks which generation engine a standalone SFX/music test
 * render (POST /api/sfx/generate) runs, in the test page's display order.
 *
 *
 * Values: see [SFXEngines].
 */
typealias SFXEngine = String

/**
 * [SFXEngine]'s wire values, in declaration order.
 */
object SFXEngines {
    const val ACE_STEP: SFXEngine = "ace_step"
    const val STABLE_AUDIO_MUSIC: SFXEngine = "stable_audio_music"
    const val STABLE_AUDIO_MEDIUM: SFXEngine = "stable_audio_medium"
    const val STABLE_AUDIO_SFX: SFXEngine = "stable_audio_sfx"
    val VALUES: List<SFXEngine> = listOf(ACE_STEP, STABLE_AUDIO_MUSIC, STABLE_AUDIO_MEDIUM, STABLE_AUDIO_SFX)
}

/** Backend catalog values - see each constant. */
object ApiCatalog {
    /**
     * Every user-selectable clone model (a book's VoiceSettings.cloneModel), in display order - backend voices.CloneModels.
     */
    val CLONE_MODELS: List<CloneModelInfoDto> = listOf(
        CloneModelInfoDto(id = "audiocpp-qwen3-0.6b", label = "Qwen3-TTS (audio.cpp)", defaultTemperature = 0.9),
        CloneModelInfoDto(id = "audiocpp-higgs-4b", label = "Higgs Audio v3 TTS 4B (audio.cpp)", defaultTemperature = 0.8),
        CloneModelInfoDto(id = "audiocpp-breeze-tts", label = "BreezeTTS 2 (audio.cpp)", defaultTemperature = 0.9),
        CloneModelInfoDto(id = "audiocpp-omnivoice", label = "OmniVoice (audio.cpp)"),
        CloneModelInfoDto(id = "audiocpp-pocket-100m", label = "PocketTTS 100M, English (audio.cpp)", defaultTemperature = 0.7),
        CloneModelInfoDto(id = "audiocpp-moss-local", label = "MOSS-TTS-Local v1.5 (audio.cpp)", defaultTemperature = 1.7),
        CloneModelInfoDto(id = "audiocpp-moss-nano", label = "MOSS-TTS-Nano 100M (audio.cpp)", defaultTemperature = 1.7),
        CloneModelInfoDto(id = "audiocpp-zipvoice", label = "ZipVoice-Distill, English/Chinese (audio.cpp)"),
        CloneModelInfoDto(id = "audiocpp-voxcpm2", label = "VoxCPM2 (audio.cpp)"),
        CloneModelInfoDto(id = "audiocpp-voxcpm1", label = "VoxCPM1 0.5B (audio.cpp)"),
        CloneModelInfoDto(id = "audiocpp-fireredtts3", label = "FireRedTTS3 Instruct (audio.cpp)"),
        CloneModelInfoDto(id = "audiocpp-firered", label = "FireRedAudio (audio.cpp)"),
        CloneModelInfoDto(id = "audiocpp-auk", label = "AuK (audio.cpp, CUDA only)"),
        CloneModelInfoDto(id = "audiocpp-auk-flash", label = "AuK-Flash (audio.cpp, CUDA only)"),
    )

    /**
     * Every VoiceDesign engine (a preset's designModel), in display order - backend voices.DesignModels.
     */
    val DESIGN_MODELS: List<DesignModelInfoDto> = listOf(
        DesignModelInfoDto(id = "breeze_tts", label = "BreezeTTS 2 (audio.cpp)", defaultGuidanceScale = 4.0, defaultTemperature = 0.9),
        DesignModelInfoDto(id = "qwen3_tts", label = "Qwen3-TTS VoiceDesign (audio.cpp)", defaultTemperature = 0.9),
        DesignModelInfoDto(id = "omnivoice", label = "OmniVoice (audio.cpp)"),
        DesignModelInfoDto(id = "fireredtts3", label = "FireRedTTS3 Instruct (audio.cpp)", defaultGuidanceScale = 1.2),
        DesignModelInfoDto(id = "firered_audio", label = "FireRedAudio (audio.cpp)", defaultGuidanceScale = 2.0),
        DesignModelInfoDto(id = "auk", label = "AuK (audio.cpp, CUDA only)", defaultGuidanceScale = 2.0),
        DesignModelInfoDto(id = "auk_flash", label = "AuK-Flash (audio.cpp, CUDA only)"),
        DesignModelInfoDto(id = "voxcpm2", label = "VoxCPM2 (audio.cpp)", defaultGuidanceScale = 2.0),
    )

    /**
     * The fixed emotion set a dialogue line can carry (Paragraph.emotion; "" is neutral), in display order - backend emotions.All.
     */
    val EMOTIONS: List<EmotionInfoDto> = listOf(
        EmotionInfoDto(id = "warm", label = "Warm"),
        EmotionInfoDto(id = "excited", label = "Excited"),
        EmotionInfoDto(id = "teasing", label = "Teasing"),
        EmotionInfoDto(id = "sad", label = "Sad"),
        EmotionInfoDto(id = "pleading", label = "Pleading"),
        EmotionInfoDto(id = "angry", label = "Angry"),
        EmotionInfoDto(id = "afraid", label = "Afraid"),
        EmotionInfoDto(id = "nervous", label = "Nervous"),
        EmotionInfoDto(id = "cold", label = "Cold"),
        EmotionInfoDto(id = "whisper", label = "Whisper"),
        EmotionInfoDto(id = "shout", label = "Shout"),
        EmotionInfoDto(id = "weary", label = "Weary"),
        EmotionInfoDto(id = "pained", label = "Pained"),
    )

    /**
     * The factory default clone model new books start with, and the fallback for a book with none set.
     */
    const val DEFAULT_CLONE_MODEL: String = "audiocpp-higgs-4b"

    /**
     * The one clone model that accepts a clone-time style instruction alongside its reference clip.
     */
    const val INSTRUCTED_CLONE_MODEL: String = "audiocpp-breeze-tts"

    /**
     * Higgs Audio - the only clone model that reads the <|prosody:pause|> tag (Paragraph.directionMarks).
     */
    const val HIGGS_CLONE_MODEL: String = "audiocpp-higgs-4b"

    /**
     * What a new custom voice preset is designed with when the request doesn't say.
     */
    const val DEFAULT_DESIGN_MODEL: String = "breeze_tts"

    /**
     * What a new book's characterVoiceMode starts as.
     */
    const val DEFAULT_CHARACTER_VOICE_MODE: String = "narrator"
}

@Serializable
data class AliasesResponseDto(
    val aliases: List<String> = emptyList(),
)

@Serializable
data class BookDetailDto(
    val id: String = "",
    val title: String = "",
    val author: String = "",
    val seriesName: String? = null,
    val seriesIndex: Double? = null,
    val coverUrl: String? = null,
    val chapterCount: Int = 0,
    val posChapterIdx: Int = 0,
    val posParagraphIdx: Int = 0,
    val posSeconds: Double = 0.0,
    val progressPercent: Double = 0.0,
    val finished: Boolean = false,
    val estimatedTotalSeconds: Double = 0.0,
    val estimateCalibrated: Boolean = false,
    val generatedPercent: Double = 0.0,
    /**
     * Preprocessing mirrors jobs.Manager.IsPipelineRunning - true while the
     * preprocessing pipeline (POST .../preprocess) is still working
     * through this book's attribution/characterization/voice-provisioning/
     * direction-tagging sequence. Set by buildBookSummary/handleListBooks,
     * not toBookSummary itself (a plain function with no Server access) -
     * see their own call sites.
     */
    val preprocessing: Boolean = false,
    /**
     * MusicEnabled mirrors store.Book.MusicEnabled - included here (not
     * just on voiceSettingsDTO, which is what actually reads/writes it)
     * purely as a read convenience so pages already holding a BookDetail/
     * BookSummary (the reader, the library) don't need a separate voice-
     * settings fetch just to know whether background music is on.
     */
    val musicEnabled: Boolean = false,
    val chapters: List<ChapterSummaryDto> = emptyList(),
)

/**
 * bookExportDTO is one export of a book: a built file, a build in
 * progress, or a failed one - an existing file stays downloadable while
 * it's rebuilt.
 */
@Serializable
data class BookExportDto(
    val id: String = "",
    val format: ExportFormat = "",
    val wordLevel: Boolean = false,
    val phraseSeconds: Double = 0.0,
    val excludeMusic: Boolean = false,
    /**
     * Latents marks a latent-only lectable transfer (createExportRequest.
     * Latents).
     */
    val latents: Boolean = false,
    /**
     * Chapters is the included chapter indexes; empty for the whole book.
     */
    val chapters: List<Int> = emptyList(),
    /**
     * ChapterLabel describes Chapters for people ("Chapters 1–40"), ""
     * for the whole book.
     */
    val chapterLabel: String = "",
    /**
     * Full is true for a whole-book export, which carries lectable's own
     * data and can be imported into another library.
     */
    val full: Boolean = false,
    /**
     * Ready means there's a built file to download (DownloadURL).
     */
    val ready: Boolean = false,
    /**
     * Stale means the book changed since the file was built.
     */
    val stale: Boolean = false,
    /**
     * Queued means its job is waiting in the job queue.
     */
    val queued: Boolean = false,
    /**
     * Rendering means its job is generating the chapters' missing audio
     * first.
     */
    val rendering: Boolean = false,
    val building: Boolean = false,
    /**
     * Progress is a running build's fraction done, 0-1.
     */
    val progress: Double = 0.0,
    /**
     * Error is the last build's failure.
     */
    val error: String? = null,
    val fileName: String? = null,
    val sizeBytes: Long? = null,
    /**
     * unix ms
     */
    val createdAt: Long? = null,
    val durationSeconds: Double? = null,
    /**
     * MissingAudio is how many paragraphs had no narration when built -
     * text-only in the file.
     */
    val missingAudio: Int? = null,
    val downloadUrl: String? = null,
)

@Serializable
data class BookManifestDto(
    val id: String = "",
    val title: String = "",
    val author: String = "",
    val coverUrl: String? = null,
    val chapterCount: Int = 0,
    /**
     * Hash is the root over the book's metadata and the chapters listed
     * in Chapters - see handleBookManifest.
     */
    val hash: String = "",
    val chapters: List<ChapterHashDto> = emptyList(),
    val posChapterIdx: Int = 0,
    val posParagraphIdx: Int = 0,
    val posSeconds: Double = 0.0,
)

@Serializable
data class BookSummaryDto(
    val id: String = "",
    val title: String = "",
    val author: String = "",
    val seriesName: String? = null,
    val seriesIndex: Double? = null,
    val coverUrl: String? = null,
    val chapterCount: Int = 0,
    val posChapterIdx: Int = 0,
    val posParagraphIdx: Int = 0,
    val posSeconds: Double = 0.0,
    val progressPercent: Double = 0.0,
    val finished: Boolean = false,
    val estimatedTotalSeconds: Double = 0.0,
    val estimateCalibrated: Boolean = false,
    val generatedPercent: Double = 0.0,
    /**
     * Preprocessing mirrors jobs.Manager.IsPipelineRunning - true while the
     * preprocessing pipeline (POST .../preprocess) is still working
     * through this book's attribution/characterization/voice-provisioning/
     * direction-tagging sequence. Set by buildBookSummary/handleListBooks,
     * not toBookSummary itself (a plain function with no Server access) -
     * see their own call sites.
     */
    val preprocessing: Boolean = false,
    /**
     * MusicEnabled mirrors store.Book.MusicEnabled - included here (not
     * just on voiceSettingsDTO, which is what actually reads/writes it)
     * purely as a read convenience so pages already holding a BookDetail/
     * BookSummary (the reader, the library) don't need a separate voice-
     * settings fetch just to know whether background music is on.
     */
    val musicEnabled: Boolean = false,
)

@Serializable
data class BookmarkDto(
    val id: String = "",
    val chapterIdx: Int = 0,
    val chapterTitle: String = "",
    val paragraphIdx: Int = 0,
    val text: String = "",
    val note: String = "",
    val createdAt: Long = 0L,
)

@Serializable
data class CanceledCountResponseDto(
    val canceled: Int = 0,
)

@Serializable
data class ChapterDetailDto(
    val idx: Int = 0,
    val title: String = "",
    val generating: Boolean = false,
    val paragraphs: List<ParagraphDto> = emptyList(),
    val content: List<ContentItemDto> = emptyList(),
    /**
     * Hash is this chapter's node in the offline-sync hash tree - see
     * chapterHash.
     */
    val hash: String = "",
)

@Serializable
data class ChapterHashDto(
    val idx: Int = 0,
    val hash: String = "",
)

@Serializable
data class ChapterMusicDto(
    val enabled: Boolean = false,
    val scored: Boolean = false,
    val regions: List<MusicRegionDto> = emptyList(),
)

@Serializable
data class ChapterSummaryDto(
    val idx: Int = 0,
    val title: String = "",
    val paragraphCount: Int = 0,
    val readyCount: Int = 0,
    /**
     * Passes is the chapter's own store.Passes, passed straight through -
     * see that type's own doc comment. Replaces the old separate
     * attributed bool/directed map[string]bool DTO fields (a holdover from
     * when direction-tagging was tracked per-clone-model); a client reads
     * passes.attribution/passes.direction directly instead.
     */
    val passes: PassesDto = PassesDto(),
    /**
     * Music* are this chapter's background-music regions: how many were
     * scored, and how many of those have a ready clip / failed. All 0 for
     * a chapter that isn't scored.
     */
    val musicRegionCount: Int = 0,
    val musicReadyCount: Int = 0,
    val musicErrorCount: Int = 0,
)

/**
 * characterIDsRequest names a set of characters for a bulk speaker action.
 */
@Serializable
data class CharacterIDsRequestDto(
    val characterIds: List<String> = emptyList(),
)

@Serializable
data class CharacterizeResponseDto(
    val summary: String = "",
    /**
     * VoiceInvalidated is true when this run changed the characterization
     * enough that the character's voice was discarded for re-rendering.
     */
    val voiceInvalidated: Boolean = false,
)

/**
 * Wire protocol - JSON text frames in both directions.
 *
 * Client -> server:
 *
 * 	{"type":"subscribe","id":"<client-chosen>","topic":"<kind>","params":{...}}
 * 	{"type":"unsubscribe","id":"<same id>"}
 *
 * id is opaque to the server and just tags every message about that
 * subscription; subscribing again with an id already in use replaces the
 * old subscription.
 *
 * Server -> client:
 *
 * 	{"type":"snapshot","id":"...","data":<full value>}
 * 	{"type":"patch","id":"...","ops":[<Op>...]}
 * 	{"type":"error","id":"...","status":404,"error":"book not found"}
 *
 * A subscription always starts with a snapshot or an error. A patch
 * applies to the value the client currently holds for that id. After an
 * error the next message for the id (if the topic recovers) is a fresh
 * snapshot, never a patch.
 */
@Serializable
data class ClientMessageDto(
    val type: String = "",
    val id: String = "",
    val topic: String = "",
    val params: JsonElement? = null,
)

/**
 * CloneModelInfo describes one clone model (store.Book.CloneModel).
 */
@Serializable
data class CloneModelInfoDto(
    val id: String = "",
    val label: String = "",
    /**
     * DefaultTemperature is the model's own sampling temperature, for a
     * model whose session reads a "temperature" option at all (nil: no
     * such knob - flow/diffusion models, OmniVoice).
     */
    val defaultTemperature: Double? = null,
)

/**
 * contentItemDTO gives the frontend chapter content in original document
 * order (text interleaved with images). Text items point back into
 * `paragraphs` by index rather than duplicating its fields, since
 * `paragraphs` is also what playback/position logic indexes into directly.
 *
 * apigen:ts-hand - the frontend models this as a discriminated union on
 * Kind instead.
 */
@Serializable
data class ContentItemDto(
    /**
     * "text" | "image" | "break"
     */
    val kind: String = "",
    /**
     * No omitempty: 0 is a valid, common paragraphIdx (the first paragraph
     * of a chapter), and omitempty would silently drop it.
     */
    val paragraphIdx: Int = 0,
    val imageUrl: String? = null,
    /**
     * Inline mirrors the referenced paragraph's own Inline (see
     * paragraphDTO.Inline) - duplicated here so the frontend's
     * content-ordering pass can decide paragraph breaks without a second
     * lookup into `paragraphs`.
     */
    val inline: Boolean = false,
)

@Serializable
data class CreateBookmarkRequestDto(
    val chapterIdx: Int = 0,
    val paragraphIdx: Int = 0,
    val note: String = "",
)

@Serializable
data class CreateExportRequestDto(
    /**
     * Format defaults to epub when empty.
     */
    val format: ExportFormat = "",
    /**
     * WordLevel highlights word by word (where the alignment matches the
     * text) instead of paragraph by paragraph.
     */
    val wordLevel: Boolean = false,
    /**
     * PhraseSeconds (word-level only) groups words into phrases at least
     * this long, so readers that track playback coarsely stay in sync at
     * high speeds - see bookexport.Options.PhraseSeconds. 0 is per word.
     */
    val phraseSeconds: Double = 0.0,
    /**
     * ExcludeMusic (whole-book only) leaves background music out - most of
     * a scored book's size; see bookexport.Options.ExcludeMusic.
     */
    val excludeMusic: Boolean = false,
    /**
     * Chapters is the chapter indexes to include; empty (or every
     * chapter) is the whole book - the only kind another library can
     * import.
     */
    val chapters: List<Int> = emptyList(),
    /**
     * AsIs skips rendering: by default the export first generates every
     * paragraph of its chapters that has no audio yet and waits for it
     * (failing if some can't be), while AsIs builds right away with
     * whatever audio exists, the rest text-only.
     */
    val asIs: Boolean = false,
    /**
     * Latents builds a latent-only lectable transfer - see
     * bookexport.Options.Latents. Always as-is; with Chapters it imports as
     * a standalone book of just those chapters.
     */
    val latents: Boolean = false,
)

@Serializable
data class CustomVoicePresetDto(
    val id: String = "",
    val name: String = "",
    val instruct: String = "",
    val refText: String = "",
    val seed: Int = 0,
    val speedMultiplier: Double = 0.0,
    val designModel: String = "",
    val createdAt: Long = 0L,
    val audioUrl: String = "",
    /**
     * Set only when tts-service failed to (re)build this preset's stable
     * reference clip; the preset is still saved and usable, just via the
     * unclamped instruct+seed fallback until this is retried (the
     * "Regenerate" button - see handleRegenerateCustomVoicePreset - or an
     * edit that saves unchanged, or waiting for tts-service's clone model
     * to come up).
     */
    val refError: String? = null,
    /**
     * GroupLabel is set only by handleListCustomVoicePresets, from
     * Store.VoicePresetGroups - the series name (or book title, if no
     * series) this preset's assigned character belongs to, so the Voices
     * page can group auto-created speaker voices by series/book instead of
     * listing every custom preset in one flat list. "" for a preset never
     * assigned to any character.
     */
    val groupLabel: String? = null,
)

@Serializable
data class CustomVoicePresetInputDto(
    val name: String = "",
    val instruct: String = "",
    val refText: String = "",
    /**
     * nil on create = server picks a random one
     */
    val seed: Int? = null,
    /**
     * nil = 1.0 (no change)
     */
    val speedMultiplier: Double? = null,
    /**
     * DesignModel: nil on create = voices.DefaultDesignModel (always
     * breeze_tts for a brand-new voice, regardless of whether its recipe
     * happens to match an existing preset's own - see voices.
     * DefaultDesignModel's own doc comment); nil on update = unchanged.
     */
    val designModel: String? = null,
)

/**
 * DesignModelInfo describes one VoiceDesign engine (Preset.DesignModel).
 */
@Serializable
data class DesignModelInfoDto(
    val id: String = "",
    val label: String = "",
    /**
     * DefaultGuidanceScale is the engine's default guidance_scale, for an
     * engine that reads one (nil: guidance is ignored). breeze_tts's is
     * this app's own override; the rest are model defaults.
     */
    val defaultGuidanceScale: Double? = null,
    /**
     * DefaultTemperature: see CloneModelInfo.DefaultTemperature.
     */
    val defaultTemperature: Double? = null,
)

/**
 * directionMarkDTO is one delivery tag pinned to where it was actually
 * inserted in p.Text, so the frontend can render an inline caret at that
 * exact point instead of just listing tags for the paragraph as a whole.
 */
@Serializable
data class DirectionMarkDto(
    /**
     * Offset is a rune (Unicode code point) index into Text, not a byte
     * offset - JavaScript string indexing is UTF-16-code-unit-based, and a
     * rune index matches that exactly for every character actually found
     * in book prose (accents, curly quotes, em-dashes - all inside the
     * Basic Multilingual Plane, one UTF-16 unit each); it would only drift
     * for a character requiring a UTF-16 surrogate pair (e.g. an emoji),
     * which no delivery tag is ever anchored beside in practice.
     */
    val offset: Int = 0,
    val tag: String = "",
)

/**
 * Emotion is one entry of the fixed emotion set.
 */
@Serializable
data class EmotionInfoDto(
    /**
     * ID is the stored/wire value (store.Paragraph.Emotion) and the
     * variant clip's file name - lowercase, stable, never renamed.
     */
    val id: String = "",
    /**
     * Label is the human-readable name shown in the UI.
     */
    val label: String = "",
)

/**
 * ErrorMessage reports a subscription that couldn't be served (bad
 * params, missing book, ...). The next message for the id, if any, is a
 * fresh snapshot.
 */
@Serializable
data class ErrorMessageDto(
    val type: String = "",
    val id: String = "",
    val status: Int = 0,
    val error: String = "",
)

/**
 * errorResponse is every non-2xx JSON body (see writeError/writeErrorCode).
 */
@Serializable
data class ErrorResponseDto(
    val error: String = "",
    /**
     * Code is set only for errors the client is expected to recover from.
     */
    val code: ErrorCode? = null,
)

/**
 * generateParagraphSFXRequest is POST .../sfx/generate's optional body.
 */
@Serializable
data class GenerateParagraphSFXRequestDto(
    val prompt: String = "",
    val durationSeconds: Double? = null,
)

/**
 * generateSFXRequest is POST /api/sfx/generate's body - the standalone
 * test surface for every generation-only "gen task" engine this app
 * wires in (ACE-Step, Stable Audio Music/SFX/Medium), one shared request
 * shape covering the union of what any of them accept. Engine selects
 * which one actually runs; every field below that engine doesn't use is
 * simply ignored (e.g. Lyrics only means anything for "ace_step"). See
 * audioworker.Worker.Music/StableAudioMusic/StableAudioSFX/
 * StableAudioMedium's own doc comments for which knobs each engine
 * actually reads and what each defaults to when left zero.
 */
@Serializable
data class GenerateSFXRequestDto(
    /**
     * Engine defaults to stable_audio_music.
     */
    val engine: SFXEngine? = null,
    val prompt: String = "",
    val lyrics: String? = null,
    val negativePrompt: String? = null,
    val durationSeconds: Double? = null,
    val numInferenceSteps: Int? = null,
    val guidanceScale: Double? = null,
    val seed: Long? = null,
)

@Serializable
data class GenerateVoiceResponseDto(
    val voicePresetId: String = "",
    val audioUrl: String = "",
)

@Serializable
data class IdResponseDto(
    val id: String = "",
)

@Serializable
data class InstanceDto(
    val id: String = "",
    val name: String = "",
)

@Serializable
data class InvalidatedResponseDto(
    val invalidated: Int = 0,
)

/**
 * jobTierRequest is PUT /api/jobs/{id}/tier's own request body - the same
 * four string values queueTaskDTO.Tier already reports (buildJobsSnapshot's
 * own toDTO), so the frontend can round-trip a row's Tier field straight
 * back as a request without a separate encoding to keep in sync.
 */
@Serializable
data class JobTierRequestDto(
    val tier: JobTier = "",
)

@Serializable
data class JobsSnapshotDto(
    val inFlight: List<QueueTaskDto> = emptyList(),
    val queued: List<QueueTaskDto> = emptyList(),
    /**
     * Paused mirrors jobs.Manager.Paused() - see handlePauseJobs/
     * handleResumeJobs, the Jobs dashboard's own pause/resume button.
     */
    val paused: Boolean = false,
)

@Serializable
data class LanguagesResponseDto(
    val languages: List<String> = emptyList(),
)

@Serializable
data class LlmTestResponseDto(
    val text: String = "",
)

@Serializable
data class LookaheadRequestDto(
    val chapterIdx: Int = 0,
    val paragraphIdx: Int = 0,
    /**
     * Optional: how many paragraphs ahead to generate. Omitted/0 means
     * jobs.LookaheadParagraphCount; clamped to jobs.MaxLookaheadParagraphCount.
     */
    val paragraphCount: Int? = null,
)

@Serializable
data class MergeCharacterRequestDto(
    /**
     * TargetName is who every one of this book's paragraphs currently
     * attributed to this character should be reattributed to instead -
     * "Narrator" (a sentinel, not a real character row) or another
     * character's exact name.
     */
    val targetName: String = "",
)

/**
 * musicRegionDTO is one store.MusicRegion, reshaped for the frontend's own
 * background-music playback engine (see store.MusicRegion's own doc
 * comment for the generation pipeline this reflects). AudioURL is only
 * set once Status is AudioReady - the same "no URL until it means
 * something" convention paragraphDTO already uses.
 */
@Serializable
data class MusicRegionDto(
    val id: String = "",
    val startIdx: Int = 0,
    val endIdx: Int = 0,
    val mood: String = "",
    /**
     * Prompt is the actual Stable Audio generation prompt ScoreMusic wrote
     * for this region (store.MusicRegion.Prompt) - Mood is just a short
     * label for compact display (table/badge text); Prompt is the fuller
     * "score" a reader can see without needing to actually hear the
     * result, surfaced by the reader's annotations view as this region's
     * own boundary marker tooltip (see ChapterSection.MusicRegionBoundary).
     */
    val prompt: String = "",
    /**
     * Ambience is the region's ambient-soundscape prompt
     * (store.MusicRegion.Ambience), mixed under the music - "" for none.
     */
    val ambience: String? = null,
    /**
     * "cut" or "continuation" - see store.MusicTransition
     */
    val transition: String = "",
    val status: AudioStatus = "",
    val error: String? = null,
    val durationSeconds: Double = 0.0,
    val audioUrl: String? = null,
)

@Serializable
data class ParagraphDto(
    val idx: Int = 0,
    val text: String = "",
    val audioStatus: AudioStatus = "",
    val audioError: String? = null,
    val durationSeconds: Double? = null,
    val audioUrl: String? = null,
    /**
     * AudioPointerSeconds is set only when this paragraph is a scare-quote
     * merge group pointer (store.AudioState.PointerOffset > 0): the time,
     * in seconds within AudioURL's own shared clip, where this paragraph's
     * own content actually begins - AudioURL itself already resolves to
     * whichever paragraph holds that shared recording (see resolveAudioID).
     * The frontend player uses this to know when playback (which it never
     * seeks or restarts at a merge group's own internal boundaries - see
     * usePlayback.ts) has reached this paragraph's own span, for
     * highlighting/position-reporting purposes only. Omitted (0) for a
     * paragraph with its own real file, which always begins at the very
     * start of AudioURL's clip.
     */
    val audioPointerSeconds: Double = 0.0,
    /**
     * Speaker is "" (never attributed) or "Narrator", or a character name -
     * see store.Paragraph.Speaker. Only actually changes this paragraph's
     * narration voice when the book has MultiVoice on (see
     * internal/narration.Resolver) and the named character has a voice
     * assigned - otherwise purely informational.
     */
    val speaker: String? = null,
    /**
     * Inline marks this paragraph as a split-out continuation of the
     * previous one, not the start of a new visual paragraph - see
     * store.Paragraph.Inline. The frontend should render consecutive
     * Inline paragraphs (and contentItemDTO's own Inline, below) joined
     * into one paragraph block rather than with a break between them,
     * while still treating each as its own playback/highlight unit.
     */
    val inline: Boolean = false,
    /**
     * IsQuote marks this as an actual quoted-dialogue span, as opposed to
     * narration/description - see store.Paragraph.IsQuote. This, not
     * Speaker being non-empty, is what tells the frontend's annotations
     * view a segment is dialogue: an unattributed quote still has
     * Speaker == "" but is dialogue all the same.
     */
    val isQuote: Boolean = false,
    /**
     * ScareQuote marks an IsQuote paragraph as NOT actually spoken dialogue
     * despite looking like it structurally - see store.Paragraph.ScareQuote.
     * Always false for a non-IsQuote paragraph.
     */
    val scareQuote: Boolean = false,
    /**
     * DescribesCharacters is which characters (if any) this paragraph's
     * narration describes - see store.Paragraph.DescribesCharacters.
     * Always empty when IsQuote is true.
     */
    val describesCharacters: List<String> = emptyList(),
    /**
     * Emotion is this paragraph's effective delivery emotion (an
     * internal/emotions id - see store.Paragraph.EffectiveEmotion), omitted
     * for neutral. Only ever set on real dialogue.
     */
    val emotion: String? = null,
    /**
     * DirectionMarks is every inline delivery tag (today only Higgs's
     * "<|prosody:pause|>") the generation text for this paragraph carries
     * under whichever clone model it's resolved to narrate through, each
     * pinned to where it's inserted in Text (see directionMarkDTO.Offset)
     * so the frontend can render an inline caret there. Empty for the
     * common case.
     */
    val directionMarks: List<DirectionMarkDto> = emptyList(),
    /**
     * PronunciationMarks is every resolved pronunciation substitution
     * active on this paragraph (e.g. "Dr." -> "Doctor"), each pinned to
     * the word it replaces (see pronunciationMarkDTO.Offset) so the
     * frontend can render a caret directly over it. Unlike DirectionMarks,
     * not clone-model-scoped - see store.Paragraph.Pronunciation's own
     * doc comment. Empty for the common case (no ambiguous abbreviation
     * found in this paragraph).
     */
    val pronunciationMarks: List<PronunciationMarkDto> = emptyList(),
    /**
     * Words is a [{text,start,end}] array from the ttsworker's
     * forced alignment (see ttsworker.Manager.Align), or "[]" before
     * alignment has run - always present (unlike the websocket push's
     * Words, which is omitted for updates that aren't about alignment)
     * since this is a full paragraph snapshot, not a patch.
     */
    val words: List<WordTimingDto> = emptyList(),
    /**
     * SFX* mirror store.Paragraph's own sound-effect test fields - see
     * its doc comments. SFXAudioURL is set only once SFXStatus ==
     * store.AudioReady, the same "URL only when actually fetchable"
     * convention AudioURL follows.
     */
    val sfxPrompt: String? = null,
    val sfxStatus: String? = null,
    val sfxError: String? = null,
    val sfxAudioUrl: String? = null,
    val sfxDurationSeconds: Double? = null,
    /**
     * SFXTriggerWord mirrors store.Paragraph.SFXTriggerWord - which word
     * (a 0-based index into Words above) playback should start the sound
     * effect at, once ready.
     */
    val sfxTriggerWord: Int? = null,
    /**
     * ContentHash/AudioHash are this paragraph's leaves in the offline-sync
     * hash tree (see manifest.go): ContentHash covers what an offline copy
     * stores about the paragraph's text and annotations, AudioHash what
     * identifies its audio (resolved voice, status, backing clip, duration,
     * pointer) - so a client can tell "refresh the metadata" apart from
     * "re-download the .wav".
     */
    val contentHash: String = "",
    val audioHash: String = "",
)

/**
 * Passes is a chapter's own book-preprocess pipeline progress
 * (chapters.passes, stored as a JSON object - the same "flexible,
 * independent facts" shape tts_tags/describes_characters/pronunciation
 * already use their own JSON columns for, rather than one forward-only
 * ChapterState enum this replaced). A struct, not a map, on the Go side so
 * call sites get a typed field (ch.Passes.Direction) instead of a
 * string-keyed lookup a typo could silently miss; the column itself
 * stays a flexible JSON object so a future pass can be added as just
 * another field with no schema change.
 */
@Serializable
data class PassesDto(
    /**
     * Attribution is set once speaker attribution
     * (internal/speakerattr.Client.AttributeChapter, via
     * httpapi.attributeChapter) has completed over the whole chapter at
     * least once, in one uninterrupted pass (possibly across several
     * paused/resumed continuations - never set on a pause or a genuine
     * failure partway through, only a full completion).
     */
    val attribution: Boolean = false,
    /**
     * Description is set once description tagging
     * (internal/speakerattr.Client.DescribeChapter, a jobs.KindDescription
     * task - see httpapi.describeChapterForJob) has completed over the
     * whole chapter, persisting which characters each narration paragraph
     * describes (Store.SetParagraphDescriptions). Its own task, dependent
     * on ScareQuote but not on Attribution.
     */
    val description: Boolean = false,
    /**
     * ScareQuote is set once scare-quote tagging
     * (internal/speakerattr.Client.ScareQuoteChapter, a jobs.KindScareQuote
     * task - see httpapi.scareQuoteChapterForJob) has completed over the
     * whole chapter, persisting Store.SetParagraphScareQuotes. Both
     * attribution and description tagging wait on this
     * (jobs.Manager.scareQuoteDependency).
     */
    val scareQuote: Boolean = false,
    /**
     * Direction is set once emotion labeling
     * (internal/speakerattr.Client.EmotionChapter, via
     * httpapi.directChapter - any clone model) has completed over the whole
     * chapter at least once, the same "full pass, not a pause/failure" contract as
     * Attribution. Fully independent of Attribution/Description - a
     * reader can trigger "Tag directions" directly on a chapter that was
     * never attributed via the per-chapter button, bypassing
     * runBookPipeline's own attribute-then-tag ordering entirely, and this
     * struct (unlike the old single ChapterState enum it replaced)
     * represents that combination just fine.
     */
    val direction: Boolean = false,
    /**
     * Pronunciation is set once pronunciation resolution
     * (internal/speakerattr.Client.ResolvePronunciation, a
     * jobs.KindPronunciation task via httpapi.pronounceChapter) has
     * completed a full pass over the chapter - Direction's own contract,
     * but its own pass.
     */
    val pronunciation: Boolean = false,
    /**
     * Music is set once internal/speakerattr.Client.ScoreMusic has
     * completed a full, uninterrupted pass over this chapter (never on a
     * pause or a genuine failure partway through) - Direction's own "full
     * pass, not a pause/failure" contract, and just as independent of
     * Attribution/Description/Direction as Direction itself is: a reader
     * can trigger background-music scoring for a chapter regardless of
     * whether it's ever been attributed/direction-tagged. Triggered by
     * httpapi.handleScoreChapterMusic (the Speakers page's per-chapter
     * button/bulk actions, book preprocessing's own music phase, or the
     * reader lazily scoring whichever chapter it's currently on) -
     * deliberately NOT gated on store.Book.MusicEnabled: that toggle only
     * controls whether a scored region's audio actually gets generated
     * (jobs.Manager.MaybeAdvanceChapterMusic), not whether scoring itself
     * can run (see Book.MusicEnabled's own doc comment).
     */
    val music: Boolean = false,
)

/**
 * PatchMessage carries the changes since the value the client holds.
 */
@Serializable
data class PatchMessageDto(
    val type: String = "",
    val id: String = "",
    /**
     * Ops' wire shape comes from Op.MarshalJSON.
     */
    val ops: List<JsonElement> = emptyList(),
)

@Serializable
data class PositionDto(
    val chapterIdx: Int = 0,
    val paragraphIdx: Int = 0,
    val seconds: Double = 0.0,
)

/**
 * pronunciationMarkDTO is one resolved pronunciation substitution pinned
 * to where it applies in p.Text, so the frontend can render a caret
 * directly over the exact word it replaces (see PronunciationCaret in
 * ParagraphText.tsx) - the pronunciation-resolution counterpart of
 * directionMarkDTO, but never clone-model-scoped (see
 * store.Paragraph.Pronunciation's own doc comment).
 */
@Serializable
data class PronunciationMarkDto(
    /**
     * Offset/Length are rune (Unicode code point) indices/counts into
     * Text, not byte ones - see directionMarkDTO.Offset's own doc comment
     * for why (JS string indexing is UTF-16-code-unit-based). Every
     * abbreviation pronunciationCandidates matches is plain ASCII, so
     * byte and rune counts are identical in practice, but converting
     * properly here costs nothing and keeps this consistent with
     * directionMarkDTO rather than relying on that coincidence.
     */
    val offset: Int = 0,
    val length: Int = 0,
    /**
     * Original is the exact text this mark covers (e.g. "Dr."), sent
     * alongside Replacement so the frontend's hover tooltip can show both
     * without needing to re-derive Original by slicing Text itself.
     */
    val original: String = "",
    val replacement: String = "",
)

@Serializable
data class QueueTaskDto(
    /**
     * ID is jobs.QueueTask.ID verbatim - the handle Cancel (DELETE
     * /api/jobs/{id}) takes, and what the frontend keys a dashboard row on.
     */
    val id: String = "",
    /**
     * Kind is one of: "voice_clone" | "voice_design" | "voice_design_preview"
     * | "voice_provision" | "speaker_attribution" | "speaker_characterization"
     * | "speech_direction" | "music_scoring" | "scare_quote_tagging" |
     * "description_tagging" (per-item work, see jobs.Kind) or
     * "pipeline_scare_quote" | "pipeline_attribution" |
     * "pipeline_description" | "pipeline_characterization" |
     * "pipeline_voice_provision" | "pipeline_direction" | "pipeline_music"
     * (one of a book's own preprocessing phases - see
     * jobs.EnqueuePipeline/toPipelineQueueTask; deliberately "pipeline_"-
     * prefixed so these can never collide with the per-item kind sharing a
     * phase's own bare name, e.g. "voice_provision").
     */
    val kind: String = "",
    /**
     * Label is a human-readable identifier for a kind that isn't chapter/
     * paragraph-scoped - the character's name for "speaker_characterization",
     * or the fixed string "Whole book" for every "pipeline_*" kind (see
     * jobs.toPipelineQueueTask) - "" for every other kind, which already has
     * a chapter/paragraph to show (see jobs.QueueTask.Label).
     */
    val label: String? = null,
    val bookId: String = "",
    val bookTitle: String = "",
    /**
     * ChapterIdx/ChapterTitle are meaningless (0/"") for
     * "speaker_characterization", which is character- rather than
     * chapter-scoped - see Label above.
     */
    val chapterIdx: Int = 0,
    val chapterTitle: String = "",
    /**
     * ParagraphIdx is meaningless (0) for the two LLM kinds
     * ("speaker_attribution"/"speaker_characterization"), which aren't
     * paragraph-scoped; for "music_live_generation" it's the first
     * paragraph of the task's one music region - the frontend should key its display on Kind
     * rather than assuming every task has a paragraph.
     */
    val paragraphIdx: Int = 0,
    val tier: JobTier = "",
    /**
     * PresetID/Instruct are "" for a "speaker_attribution" task, and for a
     * "voice_design" task PresetID alone is "" (a pure custom instruct with
     * no preset backing it) - the frontend resolves PresetID to a friendly
     * name against the built-in and custom preset lists it already fetches
     * elsewhere, falling back to Instruct when there's no preset to resolve.
     */
    val presetId: String = "",
    val instruct: String = "",
    /**
     * Attempt is jobs.QueueTask.Attempt verbatim - 0 for a task on its
     * first ever dispatch, only bumped by a genuine failure-retry, never
     * by a cooperative pause (see its own doc comment). The frontend uses
     * this to tell "this is stuck retrying after real failures" apart
     * from "this is just slowly working through a long chapter one batch
     * at a time" - both can look identical (the same row reappearing
     * over and over) without it.
     */
    val attempt: Int = 0,
    /**
     * Emotion is jobs.QueueTask.Emotion verbatim - the emotion variant a
     * clone task's line generates in, "" for neutral.
     */
    val emotion: String? = null,
)

/**
 * queuedResponse is every 202 body: how many background tasks the request
 * enqueued (1 for a single-item enqueue, even if it joined one already
 * queued). A mutation with nothing to report answers 204 instead - see
 * writeNoContent.
 */
@Serializable
data class QueuedResponseDto(
    val queued: Int = 0,
)

@Serializable
data class ReattributeSpeakerRequestDto(
    /**
     * Name is the speaker being eliminated - either a real character's
     * exact name, or literally "Unknown" (the sentinel store.Paragraph.
     * Speaker carries for a quoted line the LLM itself couldn't resolve -
     * see that field's own doc comment). Unlike merge, there's no separate
     * characterId in the path: Unknown has no characters-table row to
     * address one by, so this endpoint is reached by name, scoped to this
     * book's own speaker table, the same way it's already keyed there (see
     * handleListSpeakers).
     */
    val name: String = "",
)

@Serializable
data class RegenerateVariantRequestDto(
    val speaker: String = "",
    val emotion: String = "",
)

@Serializable
data class ReimportChapterResponseDto(
    val title: String = "",
    val paragraphs: Int = 0,
)

@Serializable
data class SearchResultDto(
    val chapterIdx: Int = 0,
    val chapterTitle: String = "",
    val paragraphIdx: Int = 0,
    val text: String = "",
)

@Serializable
data class SetCharacterAliasesRequestDto(
    val aliases: List<String> = emptyList(),
)

@Serializable
data class SetCharacterInvalidRequestDto(
    val invalid: Boolean = false,
)

@Serializable
data class SetCharacterVoiceRequestDto(
    val voicePresetId: String = "",
)

@Serializable
data class SetParagraphDescriptionRequestDto(
    val from: String = "",
    val to: String = "",
)

@Serializable
data class SetParagraphEmotionRequestDto(
    val emotion: String = "",
)

@Serializable
data class SetParagraphSFXPromptRequestDto(
    val prompt: String = "",
    /**
     * TriggerWord, when non-nil, also sets which word (a 0-based index
     * into this paragraph's own forced-alignment Words) playback should
     * start the sound effect at - see store.Paragraph.SFXTriggerWord.
     * Folded into this same request rather than a separate endpoint since
     * the frontend's SFX panel always edits both together (see
     * ChapterSection.tsx's own word-picker).
     */
    val triggerWord: Int? = null,
)

@Serializable
data class SetParagraphScareQuoteRequestDto(
    val scareQuote: Boolean = false,
)

@Serializable
data class SetParagraphSpeakerRequestDto(
    val speaker: String = "",
)

/**
 * SnapshotMessage carries a topic's full current value.
 */
@Serializable
data class SnapshotMessageDto(
    val type: String = "",
    val id: String = "",
    val data: JsonElement? = null,
)

/**
 * speakerDTO is one row of a book's speaker table (GET
 * .../speakers): every speaker actually attributed in the book so far,
 * including a synthesized "Narrator" row for unattributed/narration
 * paragraphs, with how much of their dialogue has generated audio. ID is
 * "" for the Narrator row (it isn't a characters table row - its voice is
 * the book's own, set via PUT .../voice) and for any speaker name a
 * paragraph carries that speakerattr produced but that never got
 * registered as a character (shouldn't normally happen - see
 * Server.attributeChapter - but this endpoint reports it rather than
 * hiding it). Previewing actual generated dialogue lives in
 * .../appearances now (one attempt per real paragraph, not a single
 * aggregate sample here), not this row.
 */
@Serializable
data class SpeakerDto(
    /**
     * "" for the Narrator row
     */
    val id: String = "",
    val name: String = "",
    val voicePresetId: String? = null,
    /**
     * Summary is the LLM's characterization of how this speaker sounds -
     * see store.Character.Summary - "" for the Narrator row (it isn't a
     * character) or a character not yet (or unsuccessfully) characterized.
     */
    val summary: String? = null,
    /**
     * RefLine is Summary's paired reference passage - see
     * store.Character.RefLine - what this character's auto-created voice
     * preset's own reference clip is actually rendered from (in place of
     * voices.DefaultRefText), written to match Summary's own pace/energy.
     * "" alongside an empty Summary, same as Summary itself.
     */
    val refLine: String? = null,
    val paragraphCount: Int = 0,
    val readyCount: Int = 0,
    /**
     * RefAudioURL previews this speaker's *own* voice preset specifically
     * (the same clip cloning generation itself uses) - unlike
     * SampleAudioURL, it's available immediately (rendered when the
     * preset was assigned - see voicerefs.EnsureFile), not only after real
     * paragraph audio has been generated. The Narrator row's own voice is
     * the book's (that's what Narrator means), so it's always set there;
     * for an actual character it's deliberately "" whenever
     * VoicePresetID is "" (nothing assigned to them yet), even though
     * their dialogue still narrates in the book's own voice in the
     * meantime - showing the book's clip here would look like "this is
     * what they sound like" rather than "nobody's voiced them yet", and
     * every un-provisioned character would show the exact same clip.
     */
    val refAudioUrl: String? = null,
    /**
     * Invalid mirrors store.Character.Invalid - this name has been ruled
     * out as a real speaker, and attribution will no longer assign it.
     */
    val invalid: Boolean = false,
    /**
     * Aliases mirrors store.Character.Aliases - other names this speaker
     * goes by.
     */
    val aliases: List<String> = emptyList(),
    /**
     * Emotions is every emotion this speaker's dialogue in this book
     * actually uses (store.Paragraph.EffectiveEmotion), in internal/emotions
     * order, each with its line count and the state of the emotion-variant
     * reference clip those lines clone from - the voice they generate under
     * right now (their own preset, or the book's). Omitted when they have
     * no emotional lines, or their voice has no preset to vary.
     */
    val emotions: List<SpeakerEmotionDto> = emptyList(),
)

@Serializable
data class SpeakerAppearanceDto(
    val bookId: String = "",
    val bookTitle: String = "",
    val chapterIdx: Int = 0,
    val chapterTitle: String = "",
    val paragraphIdx: Int = 0,
    val text: String = "",
    /**
     * AudioURL is set only once this specific paragraph's audio is ready
     * under whatever voice it currently resolves to (its own book's
     * MultiVoice/character-voice setup, same resolution generation itself
     * uses) - "" otherwise, in which case the frontend offers to generate
     * it instead of playing it.
     */
    val audioUrl: String? = null,
)

/**
 * speakerEmotionDTO is one emotion a speaker uses - see
 * speakerDTO.Emotions.
 */
@Serializable
data class SpeakerEmotionDto(
    val emotion: String = "",
    val label: String = "",
    val count: Int = 0,
    /**
     * Status is "ready" (variant rendered - AudioURL plays it),
     * "pending" (not rendered yet: it renders lazily the first time one of
     * these lines generates), or "failed" (couldn't be rendered; these
     * lines clone from the base clip instead).
     */
    val status: String = "",
    val audioUrl: String? = null,
)

/**
 * SubscribeMessage starts (or restarts) a subscription.
 */
@Serializable
data class SubscribeMessageDto(
    val type: String = "",
    /**
     * ID is chosen by the client and echoed on every reply.
     */
    val id: String = "",
    val topic: String = "",
    val params: JsonElement? = null,
)

@Serializable
data class TestCloneInstructRequestDto(
    /**
     * BaseID is an existing voice (built-in or custom) whose already-
     * rendered reference clip is cloned from - the timbre/identity this
     * preview keeps constant.
     */
    val baseId: String = "",
    /**
     * Instruct is the clone-time style instruction sent alongside BaseID's
     * reference clip - what this preview is actually testing.
     */
    val instruct: String = "",
    val text: String = "",
    /**
     * CloneModel is which clone model to preview through - the editor
     * always sends breeze_tts here (the one family that actually honors
     * Instruct alongside a reference clip - see audioworker.cloneFamily.
     * instructOption). "" defers to previewCloneModel's default, same as
     * testVoiceRequest.CloneModel.
     */
    val cloneModel: String? = null,
    /**
     * GuidanceScale, when set, overrides the breeze_tts clone family's own
     * configured instruct-time guidance_scale (LECTABLE_AUDIOCPP_BREEZE_CLONE_GUIDANCE_SCALE,
     * audioworker.breezeCloneGuidanceScale) for this one preview call - lets
     * the editor's own "guidance scale" test field experiment with values
     * live, without a server restart/env var change. "" defers to that
     * configured default, same as every other caller of Worker.Generate.
     */
    val guidanceScale: String? = null,
)

/**
 * testLLMRequest is POST /api/llm/test's body - a raw system+user prompt
 * pair, no speakerattr-specific framing.
 */
@Serializable
data class TestLLMRequestDto(
    val systemPrompt: String? = null,
    val userPrompt: String = "",
    val temp: Double? = null,
    val maxTokens: Int? = null,
)

@Serializable
data class TestVoiceDesignRequestDto(
    val instruct: String = "",
    /**
     * Seed nil = tts-service picks one at random (fine for a quick
     * "surprise me" listen, but that render can't be reused on save - see
     * handleCreateCustomVoicePreset - since nothing here knows what seed
     * it landed on). The editor pins a seed for a brand-new voice up
     * front specifically so Test and Save always agree on one.
     */
    val seed: Int? = null,
    val text: String = "",
    /**
     * DesignModel previews a specific VoiceDesign engine before saving -
     * "" defers to the worker's own process-wide default, same as an
     * unset preset field.
     */
    val designModel: String? = null,
    /**
     * GuidanceScale, when set, overrides the design engine's own guidance
     * strength for this one preview (nil for the engine's default). A
     * preview rendered this way is never cached for reuse on save - a saved
     * preset has no guidance setting of its own, so its clip is always
     * rendered at the engine's default.
     */
    val guidanceScale: Double? = null,
    /**
     * Temperature, when set, overrides the design engine's own sampling
     * temperature for this one preview (nil for the engine's default) -
     * same never-cached-for-save rule as GuidanceScale.
     */
    val temperature: Double? = null,
)

@Serializable
data class TestVoiceRequestDto(
    val text: String = "",
    /**
     * CloneModel is which clone model to preview the voice through - a
     * preset has none of its own (that's each book's choice). "" defers to
     * previewCloneModel's default.
     */
    val cloneModel: String? = null,
    /**
     * Temperature, when set, overrides the clone model's own sampling
     * temperature for this one test (nil for the model's default).
     */
    val temperature: Double? = null,
)

@Serializable
data class TopicParamsDto(
    val bookId: String = "",
    val chapterIdx: Int? = null,
    val characterId: String = "",
)

/**
 * UnsubscribeMessage ends a subscription.
 */
@Serializable
data class UnsubscribeMessageDto(
    val type: String = "",
    val id: String = "",
)

@Serializable
data class UpdateBookmarkRequestDto(
    val note: String = "",
)

@Serializable
data class VoicePresetDto(
    val id: String = "",
    val name: String = "",
    val instruct: String = "",
    val seed: Int = 0,
    @SerialName("ref_text")
    val refText: String = "",
    @SerialName("speed_multiplier")
    val speedMultiplier: Double = 0.0,
    val designModel: String = "",
    val audioUrl: String = "",
    /**
     * RefError is only ever set by handleRegeneratePreset's own response -
     * handleVoicePresets never renders a preset's clip as part of listing,
     * so it has nothing to report here and always leaves this "" (omitted).
     */
    val refError: String? = null,
)

/**
 * voicePresetsDTO is GET /api/voices/presets: the built-in presets plus
 * which one is the factory default.
 */
@Serializable
data class VoicePresetsDto(
    val default: String = "",
    val presets: List<VoicePresetDto> = emptyList(),
)

/**
 * voiceSettingsDTO is a book's (or the default) voice: what the client
 * sets, plus the seed the server derives from the preset.
 */
@Serializable
data class VoiceSettingsDto(
    val presetId: String = "",
    val instruct: String = "",
    val language: String = "",
    /**
     * CloneModel is which clone model narrates the book - every voice in
     * it, narrator and characters alike (store.Book.CloneModel) - or, for
     * the default voice, the clone model a newly created book starts with.
     * "" on update leaves the current value unchanged.
     */
    val cloneModel: String = "",
    /**
     * CharacterVoiceMode - see store.CharacterVoiceMode's own doc comment
     * for the four possible values ("narrator"/"assigned"/
     * "instruct_unassigned"/"instruct_all") and what each means. Characters
     * and their voice assignments (GET/PUT /api/books/{id}/characters/...)
     * can be set up regardless of this setting; it's what actually turns
     * those assignments (or, for the two instruct_* modes, a character's
     * own characterization) into different narration voices during
     * generation. The two instruct_* modes only actually change anything
     * for a book whose clone model is breeze_tts - a no-op
     * otherwise (same as "assigned" for that character).
     */
    val characterVoiceMode: CharacterVoiceMode = "",
    /**
     * SpeechDirection opts this book into waiting for speech-direction
     * tagging (store.Passes.Direction) before generating a chapter's
     * audio - see store.Book.SpeechDirection and jobs.Manager's
     * speechDirectionDependency. Off by default: most books never touch
     * direction tagging, so nothing should pay an LLM-pass delay before
     * its first audio unless a reader explicitly opts in.
     */
    val speechDirection: Boolean = false,
    /**
     * MusicEnabled is the reader-facing background-music toggle - see
     * store.Book.MusicEnabled's own doc comment for why this is book-wide
     * rather than per-chapter like Passes.Music itself. Off by default.
     */
    val musicEnabled: Boolean = false,
    val seed: Int = 0,
)

/**
 * voiceSettingsUpdate is the PUT body for a book's/the default voice -
 * every voiceSettingsDTO field the client controls (seed is derived from
 * the preset server-side). A full replace, except cloneModel.
 */
@Serializable
data class VoiceSettingsUpdateDto(
    val presetId: String = "",
    val instruct: String = "",
    val language: String = "",
    /**
     * CloneModel is which clone model narrates the book - every voice in
     * it, narrator and characters alike (store.Book.CloneModel) - or, for
     * the default voice, the clone model a newly created book starts with.
     * "" on update leaves the current value unchanged.
     */
    val cloneModel: String = "",
    /**
     * CharacterVoiceMode - see store.CharacterVoiceMode's own doc comment
     * for the four possible values ("narrator"/"assigned"/
     * "instruct_unassigned"/"instruct_all") and what each means. Characters
     * and their voice assignments (GET/PUT /api/books/{id}/characters/...)
     * can be set up regardless of this setting; it's what actually turns
     * those assignments (or, for the two instruct_* modes, a character's
     * own characterization) into different narration voices during
     * generation. The two instruct_* modes only actually change anything
     * for a book whose clone model is breeze_tts - a no-op
     * otherwise (same as "assigned" for that character).
     */
    val characterVoiceMode: CharacterVoiceMode = "",
    /**
     * SpeechDirection opts this book into waiting for speech-direction
     * tagging (store.Passes.Direction) before generating a chapter's
     * audio - see store.Book.SpeechDirection and jobs.Manager's
     * speechDirectionDependency. Off by default: most books never touch
     * direction tagging, so nothing should pay an LLM-pass delay before
     * its first audio unless a reader explicitly opts in.
     */
    val speechDirection: Boolean = false,
    /**
     * MusicEnabled is the reader-facing background-music toggle - see
     * store.Book.MusicEnabled's own doc comment for why this is book-wide
     * rather than per-chapter like Passes.Music itself. Off by default.
     */
    val musicEnabled: Boolean = false,
)

/**
 * wordTimingDTO is one element of paragraphDTO.Words, which is passed
 * through as raw JSON from the stored forced alignment rather than
 * decoded; this documents that shape for cmd/apigen. start/end are
 * seconds within the paragraph's own clip. No confidence field: the
 * aligner hardcodes it to 0 upstream.
 */
@Serializable
data class WordTimingDto(
    val text: String = "",
    val start: Double = 0.0,
    val end: Double = 0.0,
)
