// Code generated by backend/cmd/apigen from backend/internal/httpapi. DO NOT EDIT.

@file:Suppress("unused")

package com.lectable.app.data.remote

import com.lectable.app.data.remote.dto.*
import okhttp3.MultipartBody
import okhttp3.ResponseBody
import retrofit2.http.Body
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.Multipart
import retrofit2.http.POST
import retrofit2.http.PUT
import retrofit2.http.Part
import retrofit2.http.Path
import retrofit2.http.Query
import retrofit2.http.Streaming

/**
 * Every backend REST route. Paths are relative; the host is injected by [DynamicBaseUrlInterceptor]. A 204 route returns Unit and a file route a streamed [ResponseBody]; any non-2xx throws retrofit2.HttpException.
 */
interface LectableApi {
    @PUT("api/bookmarks/{id}")
    suspend fun updateBookmark(
        @Path("id") id: String,
        @Body body: UpdateBookmarkRequestDto,
    ): Unit

    @DELETE("api/bookmarks/{id}")
    suspend fun deleteBookmark(
        @Path("id") id: String,
    ): Unit

    @Multipart
    @POST("api/books")
    suspend fun uploadBook(
        @Part file: MultipartBody.Part? = null,
    ): BookSummaryDto

    /**
     * handleListBooks batch-fetches every book's chapter summaries and
     * narration stats in two queries total (one per store.ListChapterSummariesForBooks/
     * BookNarrationStatsForBooks call), not two queries per book -
     * buildBookSummary's own per-book pair of queries is fine for the
     * single-book callers (upload, get-book), but looping it once per book
     * here meant 2*N serialized whole-book scans on the single shared DuckDB
     * connection (internal/store's own doc comment) every time the library
     * page loaded, stalling every other concurrent request behind whichever
     * scan was running.
     */
    @GET("api/books")
    suspend fun listBooks(): List<BookSummaryDto>

    @GET("api/books/{id}")
    suspend fun getBook(
        @Path("id") id: String,
    ): BookDetailDto

    @DELETE("api/books/{id}")
    suspend fun deleteBook(
        @Path("id") id: String,
    ): Unit

    /**
     * handleDeleteBookAudio deletes every generated audio file for book - the
     * reader's own "Delete generated audio" button, for reclaiming disk space
     * or forcing a full regenerate, without touching the book's text,
     * chapters, speaker attribution, or voice settings (unlike handleDeleteBook,
     * which removes the whole book, or handleDeleteBookSpeakerData, which
     * clears attribution/characters instead of audio). Every paragraph reports
     * pending again on the next fetch - store.DeleteBookAudio drops every
     * paragraph_audio row for this book across every voice_id it's ever been
     * generated under, not just the book's current one, and the actual .wav
     * files live under one shared per-book directory regardless of voice_id
     * (see audiopath.ParagraphFile/VoiceDir), so removing that directory
     * wholesale - same call handleDeleteBook itself uses - covers all of them
     * in one step rather than needing to enumerate voice_ids.
     */
    @DELETE("api/books/{id}/audio")
    suspend fun deleteBookAudio(
        @Path("id") id: String,
    ): Unit

    @GET("api/books/{id}/bookmarks")
    suspend fun listBookmarks(
        @Path("id") id: String,
    ): List<BookmarkDto>

    /**
     * handleCreateBookmark flags a paragraph (addressed the same way the rest
     * of the public API does, by chapterIdx/paragraphIdx rather than its
     * internal id) as bookmarked, or updates its note if it already is - see
     * Store.UpsertBookmark.
     */
    @POST("api/books/{id}/bookmarks")
    suspend fun createBookmark(
        @Path("id") id: String,
        @Body body: CreateBookmarkRequestDto,
    ): IdResponseDto

    /**
     * handleBulkAction is POST /api/books/{id}/bulk/{action}?scope=rest|all -
     * the Speakers page's whole-book buttons, each queued as one jobs.BulkGroup
     * (Kind "pipeline_bulk_<action>") wrapping every per-chapter/per-character
     * task it fans out into, rather than the client firing one request (and
     * getting one Jobs row) per chapter. Canceling or promoting that one row
     * covers the whole action - see jobs.BulkGroup.
     *
     * action is a chapterBulkPasses key, or one of:
     *   - "generate": narration audio for every chapter (jobs.Manager.
     *     EnqueueBookGenerate - only not-yet-ready paragraphs, so scope is moot)
     *   - "music_generation": missing music for every eligible chapter
     *     (jobs.Manager.EnqueueBookMusicGeneration; scope is moot)
     *   - "characterization": re-characterize every valid character
     *   - "voices": rest provisions characters with no voice for the book's clone
     *     model yet; all force-regenerates every character's voice
     *
     * 202 {"queued": n} with how many chapters/characters the group covers (0,
     * with nothing enqueued, if there's nothing to do). A repeat click while the
     * same action+scope is still queued/in flight is a no-op.
     */
    @POST("api/books/{id}/bulk/{action}")
    suspend fun bulkAction(
        @Path("id") id: String,
        @Path("action") action: BulkAction,
        @Query("scope") scope: BulkScope? = null,
    ): QueuedResponseDto

    @GET("api/books/{id}/chapters/{idx}")
    suspend fun getChapter(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): ChapterDetailDto

    /**
     * handleAttributeSpeakers enqueues speaker attribution for one chapter,
     * explicitly triggered by the reader (not automatic) - see
     * backend/CLAUDE.md's "Speaker attribution" section. Fire-and-forget
     * (202 Accepted, no result body): attribution runs the LLM over a whole
     * chapter in batches and can take minutes, and SpeakersPage's "Attribute
     * all" fires one of these per unattributed chapter in a book at once, so
     * blocking this request on the actual run (as an earlier version did)
     * meant holding up to one HTTP connection open per chapter in the book for
     * as long as the whole book took to attribute - see
     * jobs.Manager.EnqueueAttribution's own doc comment for the full story.
     * Progress is observable via GET /api/jobs and by refetching this book's
     * speaker table once a chapter's task clears.
     */
    @POST("api/books/{id}/chapters/{idx}/attribute-speakers")
    suspend fun attributeSpeakers(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleDeleteChapterAudio is handleDeleteBookAudio's single-chapter
     * counterpart - the reader-facing chapter-header "Clear generation" button,
     * for resetting just one chapter's narration (e.g. after reassigning
     * speakers, or to force a clean re-render) without wiping the whole book's
     * progress.
     */
    @DELETE("api/books/{id}/chapters/{idx}/audio")
    suspend fun deleteChapterAudio(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): Unit

    /**
     * handleGenerateChapter enqueues background TTS generation for one
     * chapter's not-yet-generated paragraphs, as a cancelable poolPipeline
     * task - see jobs.Manager.EnqueueChapter's own doc comment.
     */
    @POST("api/books/{id}/chapters/{idx}/generate")
    suspend fun generateChapter(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleGenerateChapterMusic queues the whole-chapter music run for one
     * chapter right now (jobs.Manager.GenerateChapterMusic) - the Speakers
     * page's per-chapter button. 202 {"queued": n} with how many regions it
     * queued (0 if every region already has music); 409 if the chapter isn't
     * scored or its narration isn't fully generated yet, since each region's
     * clip is sized to its own narration.
     */
    @POST("api/books/{id}/chapters/{idx}/generate-music")
    suspend fun generateChapterMusic(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleGetChapterMusic serves GET .../chapters/{idx}/music - the reader's
     * own background-music mixer watches the same data live as the
     * "chapterMusic" topic (see registerLiveTopics), and the Speakers page's chapter
     * table reads book.chapters[idx].passes.music/store.Book.MusicEnabled
     * directly (already part of the book fetch it already has) rather than
     * this endpoint, which exists for the regions themselves.
     */
    @GET("api/books/{id}/chapters/{idx}/music")
    suspend fun getChapterMusic(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): ChapterMusicDto

    /**
     * handleSetParagraphDescription reassigns one paragraph's description
     * attribution from one character to another - the Speakers page's
     * per-character "descriptions" list's own counterpart to
     * handleSetParagraphSpeaker for actual dialogue lines. A narration
     * paragraph the Describe pass (internal/speakerattr.Client.DescribeChapter)
     * tagged as describing From gets From removed from its
     * describes_characters list and To added instead - any *other* character
     * this same paragraph also describes (DescribesCharacters is a list, not a
     * single value - a paragraph can describe more than one person) is left
     * untouched. "" and "Narrator" for To both mean "remove this description
     * entirely, describing no one now" (mirrors handleSetParagraphSpeaker's own
     * Narrator-means-empty convention) - there's no "To must be non-Narrator"
     * restriction the way speaker attribution requires IsQuote, since narration
     * describing a character is exactly what this feature already is. A
     * non-empty, non-Narrator To is registered as a real character first if it
     * wasn't one already (UpsertCharacter is idempotent), same as
     * handleSetParagraphSpeaker. Refuses to attach a description to a quoted
     * paragraph (mirrors DescribesCharacters' own doc comment: only narration
     * is ever tagged as a description, never a quoted line).
     */
    @PUT("api/books/{id}/chapters/{idx}/paragraphs/{pidx}/description")
    suspend fun setParagraphDescription(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Path("pidx") pidx: Int,
        @Body body: SetParagraphDescriptionRequestDto,
    ): Unit

    /**
     * handleSetParagraphEmotion is a reader's manual override of one dialogue
     * line's emotion (an internal/emotions id, or "" for neutral) - the
     * annotations view's right-click menu. Like handleSetParagraphScareQuote,
     * it invalidates and immediately re-enqueues the line's audio when its
     * effective emotion actually changes, since that picks a different
     * reference clip (lazily rendering the variant first - see
     * jobs.Manager.variantClipDependency). 400 for narration or an unknown
     * emotion.
     */
    @PUT("api/books/{id}/chapters/{idx}/paragraphs/{pidx}/emotion")
    suspend fun setParagraphEmotion(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Path("pidx") pidx: Int,
        @Body body: SetParagraphEmotionRequestDto,
    ): Unit

    /**
     * handleGenerateParagraphSFX renders (or re-renders) one paragraph's sound
     * effect - via Stable Audio's own SFX checkpoint (StableAudioSFX) - from
     * its own saved sfx_prompt, or from a prompt sent inline in this same
     * request (persisted first, same as if handleSetParagraphSFXPrompt had
     * just been called) - a convenience so the test UI can save+generate in
     * one click. Dispatched through jobs.Manager.EnqueueSFXGeneration
     * (KindSFXGeneration, poolSFX) rather than calling s.TTS.StableAudioSFX
     * directly and blocking this request on it: it's a multi-step diffusion
     * call, materially slower than an ordinary clone, and this way it
     * properly shares poolSFX's concurrency limit and TTS/LLM-pool mutual
     * exclusion with every other real generation task instead of racing the
     * worker uncoordinated - returns 202 immediately, same shape as
     * handleRegenerateParagraph. The frontend picks up completion via
     * chapterQueryOptions' own poll (see api/queries.ts) rather than a
     * dedicated push.
     */
    @POST("api/books/{id}/chapters/{idx}/paragraphs/{pidx}/generate-sfx")
    suspend fun generateParagraphSFX(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Path("pidx") pidx: Int,
        @Body body: GenerateParagraphSFXRequestDto,
    ): QueuedResponseDto

    /**
     * handleRegenerateParagraph re-renders one already-generated paragraph
     * from scratch - the reader didn't like how a specific line came out, not
     * the normal "this hasn't been generated yet" path handleGenerateChapter
     * covers.
     */
    @POST("api/books/{id}/chapters/{idx}/paragraphs/{pidx}/regenerate")
    suspend fun regenerateParagraph(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Path("pidx") pidx: Int,
    ): QueuedResponseDto

    /**
     * handleSetParagraphScareQuote lets a reader directly mark (or unmark) one
     * quoted paragraph as a scare quote - handleSetParagraphSpeaker/
     * handleSetParagraphDescription's own counterpart for
     * speakerattr.Client.ScareQuoteChapter's judgment, for the case a reader
     * spots one it missed (or wrongly flagged) live while reading, rather than
     * waiting on - or overriding - the automatic pass. Refuses a non-quoted
     * paragraph the same way handleSetParagraphSpeaker refuses attributing a
     * non-quoted one to a character - see store.Paragraph.ScareQuote's own
     * "always false for a non-IsQuote paragraph" invariant.
     *
     * Unlike handleSetParagraphSpeaker/handleSetParagraphDescription (which
     * leave any already-generated audio untouched, requiring a separate
     * explicit "regenerate" call), this immediately invalidates this
     * paragraph's own audio - a deliberate, live correction is exactly the
     * "the reader didn't like this line" shape EnqueueParagraphRegenerate
     * already treats as urgent, not a passive attribute edit - and, via
     * expandToInlineSets, every other paragraph in its own inline paragraph
     * set too, since toggling this one flag can change whether that whole
     * Inline-linked run is eligible for scare-quote merging - see
     * expandToInlineSets' own doc comment for why a merge-mate's already-
     * generated audio can otherwise go stale forever. Also re-enqueues every
     * invalidated member at urgent priority (the same EnqueueParagraphRegenerate
     * call handleRegenerateParagraph itself uses) rather than just invalidating
     * and leaving them AudioPending - a reader correcting a scare quote live
     * wants to hear the fix, not stumble onto silent/missing audio the next
     * time they reach this line, which is all invalidation alone would do
     * (nothing scans for AudioPending rows on its own - see
     * EnqueueLookahead/EnqueueChapter, the only other paths that dispatch
     * generation). Calling it once per inline-set member, not just the toggled
     * paragraph, is deliberately redundant with pushResolvedTask/
     * scareQuoteMergeGroup's own merge-group expansion - EnqueueParagraphRegenerate
     * only expands the one paragraph passed to it, so a merge-mate that isn't
     * itself re-enqueued here would otherwise sit invalidated with nothing to
     * generate it; pushTask's dedup (keyed off a merge group's own first
     * member) makes the resulting duplicate pushes collapse harmlessly.
     */
    @PUT("api/books/{id}/chapters/{idx}/paragraphs/{pidx}/scare-quote")
    suspend fun setParagraphScareQuote(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Path("pidx") pidx: Int,
        @Body body: SetParagraphScareQuoteRequestDto,
    ): Unit

    /**
     * handleSetParagraphSFXPrompt saves (without generating) one paragraph's
     * sound-effect test prompt and/or trigger word - a plumbing-only test
     * surface for now (see backend/CLAUDE.md's "SFX sound effects" section on
     * why the prompt is reader-entered rather than automatically detected).
     * Doesn't touch any already-generated clip or status.
     */
    @PUT("api/books/{id}/chapters/{idx}/paragraphs/{pidx}/sfx-prompt")
    suspend fun setParagraphSFXPrompt(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Path("pidx") pidx: Int,
        @Body body: SetParagraphSFXPromptRequestDto,
    ): Unit

    /**
     * handleSetParagraphSpeaker corrects one paragraph's speaker attribution
     * directly, addressed the same way handleRegenerateParagraph is (book +
     * chapter idx + paragraph idx) - the Speakers page's per-character
     * "appearances" list uses this to fix one individually misattributed line
     * (a model mistake, or a line that's actually someone else's) without
     * touching any other paragraph currently sharing that same (wrong)
     * speaker, unlike handleMergeCharacter's whole-character reassignment
     * (Store.ReassignCharacterSpeaker). "" and "Narrator" are equivalent (see
     * store's own paragraphs.speaker column comment) and both normalize to the
     * "" stored value handleMergeCharacter's own Narrator case already uses. A
     * non-empty, non-Narrator name is registered as a real character first if
     * it wasn't one already (UpsertCharacter is idempotent), same as
     * handleMergeCharacter, so reassigning to a brand-new name here works
     * exactly like discovering it via attribution. Refuses to attribute a
     * non-Narrator speaker to a paragraph that isn't actually quoted dialogue
     * (IsQuote) - the same invariant httpapi.attributeChapter enforces
     * (narration *about* a character isn't them speaking), still worth
     * guarding here even though every paragraph reachable through an
     * "appearances" list already passed it once at attribution time.
     */
    @PUT("api/books/{id}/chapters/{idx}/paragraphs/{pidx}/speaker")
    suspend fun setParagraphSpeaker(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Path("pidx") pidx: Int,
        @Body body: SetParagraphSpeakerRequestDto,
    ): Unit

    /**
     * handleReimportChapter re-parses one chapter from the book's source epub
     * and replaces its content (store.ReplaceChapterContent) - for applying a
     * parser fix to the chapters that need it without deleting the whole book
     * and losing every other chapter's attribution, manual fixes, and audio.
     * The source is the epub kept at upload (audiopath.SourceEpubFile), or a
     * multipart "file" field, which also becomes the kept copy (for books
     * imported before uploads were kept, or to swap in a corrected epub).
     *
     * The re-parsed book must have the same number of chapters, so idx still
     * names the same chapter; its title must match too unless ?force=true
     * (a parser change can legitimately retitle a chapter). Those two
     * recoverable 409s carry a code (writeErrorCode): "no_source_epub" and
     * "title_mismatch". Every queued and
     * in-flight job for the chapter is cancelled first (jobs.Manager.
     * CancelChapter) - 409 if something is still running after
     * reimportCancelWait. Everything derived from the old text goes: audio,
     * speakers, emotions, pronunciation, SFX, music regions, pass flags. The
     * chapter then needs preprocessing again like a fresh import.
     */
    @Multipart
    @POST("api/books/{id}/chapters/{idx}/reimport")
    suspend fun reimportChapter(
        @Path("id") id: String,
        @Path("idx") idx: Int,
        @Query("force") force: String? = null,
        @Part file: MultipartBody.Part? = null,
    ): ReimportChapterResponseDto

    /**
     * handleResolvePronunciation queues a KindPronunciation task for one
     * chapter - handleRetagScareQuotes' counterpart, for any clone model.
     * Always re-runs, even if the chapter was already resolved.
     */
    @POST("api/books/{id}/chapters/{idx}/resolve-pronunciation")
    suspend fun resolvePronunciation(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleRetagDescriptions queues a KindDescription task for one chapter -
     * the Speakers page's own "Retag descriptions" button. Always re-runs, even
     * if the chapter was already described. Fire-and-forget (202), the same
     * shape as handleAttributeSpeakers; the task waits on the chapter's
     * scare-quote tagging first (jobs.Manager.scareQuoteDependency), and
     * progress shows up on the Jobs dashboard.
     */
    @POST("api/books/{id}/chapters/{idx}/retag-descriptions")
    suspend fun retagDescriptions(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleRetagScareQuotes queues a KindScareQuote task for one chapter -
     * handleRetagDescriptions' counterpart. Always re-runs, even if the chapter
     * was already tagged.
     */
    @POST("api/books/{id}/chapters/{idx}/retag-scare-quotes")
    suspend fun retagScareQuotes(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleScoreChapterMusic is POST .../chapters/{idx}/score-music - triggers
     * internal/speakerattr.Client.ScoreMusic for one chapter, handleAttributeSpeakers/
     * handleTagDirections' own exact fire-and-forget shape. Explicit and
     * always allowed regardless of store.Book.MusicEnabled (the Speakers
     * page's per-row/bulk buttons can score a chapter's music the same way
     * they can attribute or direction-tag one, whether or not the reader has
     * ever turned the book-wide toggle on) - MusicEnabled only gates whether
     * jobs.Manager.MaybeAdvanceChapterMusic goes on to actually *generate* a
     * scored region's audio, not whether scoring itself can run. Re-running
     * this for an already-scored chapter re-scores it from scratch
     * (scoreChapterMusic's own Store.ClearMusicRegions), the same "always
     * allow a fresh run" shape the direction-tagging button already has - but
     * re-running (or auto-retriggering, e.g. maybeScoreChapterMusic) a chapter
     * that's only partially scored resumes from where the last attempt left
     * off instead, rather than wiping and redoing that real work; see
     * scoreChapterMusic's own doc comment for why.
     */
    @POST("api/books/{id}/chapters/{idx}/score-music")
    suspend fun scoreChapterMusic(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleTagDirections enqueues speech-direction tagging for one chapter,
     * explicitly triggered by the reader - see directChapter's own doc comment
     * for why this isn't chained after attribution automatically the way
     * describeChapter is. Fire-and-forget (202 Accepted, no result body),
     * mirroring handleAttributeSpeakers exactly: tagging runs the LLM over a
     * whole chapter in batches and can take a while, so this shouldn't hold a
     * request open for it - see jobs.Manager.EnqueueAttribution's own doc
     * comment for the fuller story behind that shape. Progress is observable
     * via GET /api/jobs.
     */
    @POST("api/books/{id}/chapters/{idx}/tag-directions")
    suspend fun tagDirections(
        @Path("id") id: String,
        @Path("idx") idx: Int,
    ): QueuedResponseDto

    /**
     * handleCharacterizeSpeakers batch-enqueues re-characterization for a list
     * of characters in one request - SpeakersPage's "Recharacterize all",
     * fire-and-forget (202 Accepted, no result body) via
     * jobs.Manager.EnqueueCharacterization rather than one blocking
     * POST .../characterize per character (see that method's own doc comment
     * for why: the browser's per-origin connection cap plus a page reload
     * mid-burst could otherwise silently drop whichever characters' requests
     * hadn't gone out yet). Unknown/already-deleted character ids are skipped,
     * not an error - a stale id in the client's own list (e.g. a character
     * merged/deleted by another tab moments earlier) shouldn't fail the rest
     * of the batch. Progress is observable the same way as any other
     * characterization - GET /api/jobs, and refetching this book's speaker
     * table once each one's task clears.
     */
    @POST("api/books/{id}/characters/characterize")
    suspend fun characterizeSpeakers(
        @Path("id") id: String,
        @Body body: CharacterIDsRequestDto,
    ): QueuedResponseDto

    /**
     * handleGenerateCharacterVoices batch-provisions a voice for every given
     * character in one request - SpeakersPage's "Generate all voices",
     * fire-and-forget (202 Accepted, no result body), the same rationale as
     * handleCharacterizeSpeakers: one request that survives the page closing,
     * not N blocking requests capped by the browser's own per-origin
     * connection limit.
     *
     * Each character's provisionCharacterVoice call runs as its own
     * jobs.Manager KindVoiceProvision task (see EnqueueVoiceProvision) rather
     * than a bare detached goroutine (an earlier version of this handler used
     * one): a goroutine calling straight into the TTS worker bypasses
     * poolGeneration's own concurrency limit and, more importantly, the
     * worker's poolGeneration/poolLLM mutual exclusion (see worker's own
     * fill) that keeps this app's two GPU-bound subsystems - the TTS worker
     * and the in-process speakerattr LLM - from running at the same time and
     * competing for VRAM. EnqueueVoiceProvision's own doc comment covers why
     * this is poolGeneration rather than poolLLM despite
     * provisionCharacterVoice itself enqueuing a KindSpeakerCharacterization
     * (poolLLM) task internally for an uncharacterized character. Already-
     * provisioned characters no-op harmlessly, same as the single-character
     * button - see provisionCharacterVoice's own doc comment; a character with
     * no dialogue/description attributed yet now still gets characterized
     * (from its name alone) and provisioned like any other, rather than
     * silently no-opping. Unknown/already-deleted
     * character ids are skipped, not an error, same reasoning as
     * handleCharacterizeSpeakers.
     */
    @POST("api/books/{id}/characters/generate-voice")
    suspend fun generateCharacterVoices(
        @Path("id") id: String,
        @Body body: CharacterIDsRequestDto,
    ): QueuedResponseDto

    /**
     * handleRegenerateCharacterVoices batch-forces a fresh reference-clip
     * render for every given character in one request - SpeakersPage's
     * "Regenerate all voices", distinct from handleGenerateCharacterVoices:
     * that one only provisions characters with no voice yet (idempotent,
     * no-ops on an already-provisioned one), this one re-renders regardless of
     * whether a cached ref already exists - see regenerateCharacterVoice. Same
     * EnqueueVoiceProvision/KindVoiceProvision shape and rationale as
     * handleGenerateCharacterVoices (its own doc comment covers the
     * poolGeneration-not-poolLLM reasoning, which applies identically here -
     * regenerateCharacterVoice can also enqueue a KindSpeakerCharacterization
     * task internally, for a character with no voice yet at all).
     */
    @POST("api/books/{id}/characters/regenerate-voice")
    suspend fun regenerateCharacterVoices(
        @Path("id") id: String,
        @Body body: CharacterIDsRequestDto,
    ): QueuedResponseDto

    /**
     * handleDeleteCharacter removes one character entirely - a scalpel next
     * to handleDeleteBookSpeakerData's sledgehammer, for cleaning up a single
     * bad attribution (a name that was never really a character - a stray
     * first-person pronoun, a generic descriptive phrase, a one-off
     * hallucination) without resetting the whole roster. Every paragraph in
     * *this* book currently attributed to them reverts to "Unknown", not ""
     * (Narrator) - see Store.ReassignCharacterSpeaker's own doc comment for
     * why: these paragraphs are still real quoted dialogue, just no longer
     * attributed to this character, and "Narrator" is reserved exclusively
     * for actual narration. Scoped to this book only; their identity/Summary,
     * every clone model's voice assignment, and every voice preset
     * auto-created for them (+ cached reference clip) are deleted for their
     * whole series scope, same split as handleDeleteBookSpeakerData.
     */
    @DELETE("api/books/{id}/characters/{characterId}")
    suspend fun deleteCharacter(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
    ): Unit

    /**
     * handleSetCharacterAliases replaces one character's aliases (store.
     * Character.Aliases) - other names they go by, which attribution folds
     * back into their name and reads in speech tags ("Albert said"). 400 for
     * an alias that names no single person (a group like "Bert and Sid", a
     * non-answer like "No one"); 409 for one that's already another valid
     * character's name or alias in this series (merge them instead).
     */
    @PUT("api/books/{id}/characters/{characterId}/aliases")
    suspend fun setCharacterAliases(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
        @Body body: SetCharacterAliasesRequestDto,
    ): AliasesResponseDto

    /**
     * handleCharacterAppearances lists every paragraph a character speaks,
     * across every book in their series (see store.SeriesScope) - backing a
     * "where does this character show up" view. bookID in the path is just
     * how the character is reached (matching every other .../characters/{id}
     * route); the character's own scope, not that one book, decides which
     * books are actually searched.
     */
    @GET("api/books/{id}/characters/{characterId}/appearances")
    suspend fun characterAppearances(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
    ): List<SpeakerAppearanceDto>

    /**
     * handleCharacterizeSpeaker force re-runs characterization for one
     * character - the Speakers page's own (and the reader-view annotation
     * legend's own) explicit "Regenerate" button, distinct from
     * provisionCharacterVoice's own lazy, characterize-once-ever behavior.
     * Unlike that path, this always re-runs even if char.Summary is already
     * set (a deliberate "redo this with a fuller sample now that there's more
     * dialogue" ask - see backend/CLAUDE.md's "Speaker attribution" section).
     *
     * Dispatched through jobs.Manager.RunCharacterization - same
     * KindSpeakerCharacterization task shape (and same TierUrgent/poolLLM
     * admission, and dedup-by-characterID against an already-in-flight run)
     * its own batch sibling handleCharacterizeSpeakers and the lazy path
     * (ensureCharacterized) both already use - rather than calling
     * characterizeVoice directly against the request's own context, which an
     * earlier version of this handler did: that bypassed the job queue
     * entirely, so a manual "Regenerate" click showed up nowhere on the Jobs
     * dashboard, couldn't join (or be joined by) a concurrent run for the same
     * character, and - the sharper bug - never respected poolGeneration/
     * poolLLM's mutual exclusion (see internal/jobs' own "Layout" section in
     * backend/CLAUDE.md), so it could run the speakerattr LLM at the exact
     * same time as ordinary TTS generation, the two GPU-bound subsystems this
     * app is otherwise careful to never let contend for VRAM at once.
     * RunCharacterization still blocks this request until the task finishes
     * (a single character's own characterization is one short LLM call, the
     * same "fine to hold the connection open" reasoning EnqueueAttribution's
     * own doc comment gives for why *that* one doesn't), so the response body
     * (summary/voiceInvalidated) is unchanged.
     *
     * See recharacterizeAndInvalidate for what happens after a successful
     * re-characterization (every clone model's assigned voice preset for the
     * character gets invalidated, not just rebuilt eagerly).
     */
    @POST("api/books/{id}/characters/{characterId}/characterize")
    suspend fun characterizeSpeaker(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
    ): CharacterizeResponseDto

    /**
     * handleCharacterDescriptions lists every paragraph that describes a
     * character's physical appearance or personality (see
     * internal/speakerattr's DescribeChapter and Store.SetParagraphDescriptions),
     * across every book in their series (see store.SeriesScope) -
     * handleCharacterAppearances' own description-tagging counterpart, same DTO
     * shape and the same "bookID in the path is just how the character is
     * reached" rationale. A description paragraph's own attributed speaker is
     * always "Narrator" (or "", pre-attribution) - see
     * Store.ParagraphsDescribing's own doc comment - so audio resolution here
     * always goes through the "Narrator" name, unlike handleCharacterAppearances'
     * own char.Name: it's previewing the narration itself, not this character's
     * own (nonexistent, for a paragraph they don't speak) dialogue.
     */
    @GET("api/books/{id}/characters/{characterId}/descriptions")
    suspend fun characterDescriptions(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
    ): List<SpeakerAppearanceDto>

    /**
     * handleGenerateCharacterVoice force-provisions a voice for one character
     * right now, rather than waiting for the lazy path
     * (jobs.Manager.provisionMissingCharacterVoices) to trigger it the next
     * time their dialogue is actually generated - the Speakers page's own
     * "Generate voice" button, for previewing/setting up a character's voice
     * ahead of time. Idempotent: if they already have one for this book's
     * clone model, provisionCharacterVoice's own fast path just returns it
     * unchanged. 409 if there still isn't enough dialogue to characterize
     * them from yet (provisionCharacterVoice returns "", nil in that case,
     * same as the lazy path silently no-ops on).
     */
    @POST("api/books/{id}/characters/{characterId}/generate-voice")
    suspend fun generateCharacterVoice(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
    ): GenerateVoiceResponseDto

    /**
     * handleSetCharacterInvalid marks (or unmarks) a character as invalid -
     * not a real speaker, so attribution stops creating/assigning the name
     * (see store.Character.Invalid). Non-destructive: the paragraphs already
     * attributed to them, their summary, and their voice assignments are all
     * left alone, so unmarking restores them exactly - Auto Split
     * (handleReattributeSpeaker, which also sets this flag) is what actually
     * moves their existing lines elsewhere.
     */
    @PUT("api/books/{id}/characters/{characterId}/invalid")
    suspend fun setCharacterInvalid(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
        @Body body: SetCharacterInvalidRequestDto,
    ): Unit

    /**
     * handleMergeCharacter folds one character into another: every paragraph
     * in this book currently attributed to them is reattributed to
     * req.TargetName instead of reverting to blank, and their own identity/
     * voice/presets are deleted for their whole series scope (see
     * deleteCharacterIdentity) - for when attribution split one person into
     * two rows (a variant spelling canonicalizeSpeakerNames didn't catch, or
     * a misattribution like a character's own name appearing as a vocative
     * in someone else's line - see backend/CLAUDE.md's "Speaker attribution"
     * section), or turns out to have just been the narrator all along.
     * Unlike handleDeleteCharacter (which always reassigns to "Unknown" -
     * see its own doc comment), this lets the caller explicitly choose
     * "Narrator" as the target too: a deliberate reader assertion ("this
     * really was narration, not a real speaker") is different from simply
     * removing a bad character with no replacement judgment made either way.
     * Both are thin wrappers over the same two steps (Store.
     * ReassignCharacterSpeaker + deleteCharacterIdentity) with a different
     * fixed/caller-supplied target; merging into another named character
     * additionally registers it as a real character first if it wasn't one
     * already (UpsertCharacter is idempotent either way - see
     * handleListSpeakers' own comment on a raw paragraph speaker that never
     * got registered).
     */
    @POST("api/books/{id}/characters/{characterId}/merge")
    suspend fun mergeCharacter(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
        @Body body: MergeCharacterRequestDto,
    ): Unit

    /**
     * handleSetCharacterVoice assigns (or, with "", clears) a character's own
     * narration voice - a character with no voice assigned still narrates in
     * the book's own voice even when book.MultiVoice is on (see
     * internal/narration.Resolver). The assignment is scoped to the *book's
     * own* resolved clone model (see store.Character's doc comment) - a
     * reader manually assigning a voice through this book's speaker table sets
     * what that character sounds like specifically when narrated through this
     * book's model, not through every clone model a character might ever be
     * narrated with.
     */
    @PUT("api/books/{id}/characters/{characterId}/voice")
    suspend fun setCharacterVoice(
        @Path("id") id: String,
        @Path("characterId") characterId: String,
        @Body body: SetCharacterVoiceRequestDto,
    ): Unit

    @Streaming
    @GET("api/books/{id}/cover")
    suspend fun getCover(
        @Path("id") id: String,
    ): ResponseBody

    @GET("api/books/{id}/exports")
    suspend fun listExports(
        @Path("id") id: String,
    ): List<BookExportDto>

    /**
     * handleCreateExport queues an export as a job-queue task (a Jobs-page
     * row, Kind "pipeline_export") - rebuilding it if one with the same
     * settings already exists. Unless AsIs, the task first renders the
     * chapters' missing audio (jobs.Manager.RenderChapters) and waits for it.
     * Progress and the result show up on the bookExports live topic.
     */
    @POST("api/books/{id}/exports")
    suspend fun createExport(
        @Path("id") id: String,
        @Body body: CreateExportRequestDto,
    ): QueuedResponseDto

    /**
     * handleDeleteExport removes an export's file, or cancels its task.
     */
    @DELETE("api/books/{id}/exports/{exportId}")
    suspend fun deleteExport(
        @Path("id") id: String,
        @Path("exportId") exportId: String,
    ): Unit

    @Streaming
    @GET("api/books/{id}/exports/{exportId}/file")
    suspend fun getExportFile(
        @Path("id") id: String,
        @Path("exportId") exportId: String,
    ): ResponseBody

    /**
     * handleGenerateBook enqueues background TTS generation for every chapter
     * in a book at once - the library page's own "Generate audio" -> "All"
     * button (LibraryPage.tsx), for a reader who wants a whole book ready to
     * listen to without opening it chapter by chapter first.
     *
     * A single call into jobs.Manager.EnqueueBookGenerate, not a loop over
     * every chapter here: that whole-book walk (and its own cancelability) now
     * lives on the Manager side, as one cancelable poolPipeline task rather
     * than this handler pushing N independent per-chapter tasks with no
     * single handle to stop them all at once - see EnqueueBookGenerate's own
     * doc comment. Fire-and-forget either way: this never itself blocks on an
     * actual TTS render or LLM call the way a preprocessing phase does, and
     * calling it twice in a row, or alongside a reader actively reading the
     * book, just re-enqueues whatever isn't already ready/generating,
     * harmlessly (EnqueueBookGenerate's own task is idempotent per book, same
     * as EnqueueChapter always was per chapter).
     */
    @POST("api/books/{id}/generate")
    suspend fun generateBook(
        @Path("id") id: String,
    ): QueuedResponseDto

    /**
     * handleGenerateRemaining enqueues background TTS generation for every
     * paragraph in a book from its current stored reading position
     * (store.Book.PosChapterIdx/PosParagraphIdx) through the end of the book -
     * the "Remaining" option on the library page's "Generate audio" button
     * (LibraryPage.tsx), alongside handleGenerateBook's "All" option. Position
     * is read server-side rather than taken from the request body: it's the
     * same value GET /api/books already returns per book, so a caller (the
     * library page, or the Android app's own long-press equivalent) needs
     * nothing beyond the book ID to mean "the rest of this book, from wherever
     * I've actually gotten to". See jobs.Manager.EnqueueRemaining.
     */
    @POST("api/books/{id}/generate-remaining")
    suspend fun generateRemaining(
        @Path("id") id: String,
    ): QueuedResponseDto

    /**
     * handleLookahead keeps some runway of generated audio ahead of wherever
     * the reader currently is, spanning into later chapters as needed rather
     * than stopping at the current chapter's end - see
     * jobs.Manager.EnqueueLookahead.
     */
    @POST("api/books/{id}/lookahead")
    suspend fun lookahead(
        @Path("id") id: String,
        @Body body: LookaheadRequestDto,
    ): QueuedResponseDto

    /**
     * handleBookManifest returns a book's offline-sync root hash plus its
     * chapter hashes. `?chapters=0,3,7` limits it to those chapters (unknown
     * indexes are just absent from the result) - a client only ever holds a
     * few chapters of a book offline, so it asks for just what it has; the
     * root then covers only that subset, which is still exactly what it needs
     * to compare against. Without the parameter, every chapter is included.
     *
     * Chapter hashes come from the stored tree (store.SyncTreeNodes) wherever
     * their inputs haven't moved, so an unchanged book costs a fingerprint
     * query plus two small reads, not a buildChapter per chapter - see "The
     * stored tree" above.
     */
    @GET("api/books/{id}/manifest")
    suspend fun bookManifest(
        @Path("id") id: String,
        @Query("chapters") chapters: String? = null,
    ): BookManifestDto

    @GET("api/books/{id}/position")
    suspend fun getPosition(
        @Path("id") id: String,
    ): PositionDto

    @PUT("api/books/{id}/position")
    suspend fun updatePosition(
        @Path("id") id: String,
        @Body body: PositionDto,
    ): Unit

    /**
     * handlePreprocessBook kicks off the preprocessing pipeline for the whole
     * book (see jobs.Manager.EnqueuePipeline) and returns
     * immediately (202) - the same fire-and-forget shape as
     * handleAttributeSpeakers/handleTagDirections, for the same reason: a
     * whole book can take anywhere from minutes to hours to fully attribute/
     * characterize/provision/tag, so nothing should hold an HTTP request (or a
     * browser connection) open for it. Progress is observable the same way
     * running each phase's own buttons individually already is - via GET
     * /api/jobs (each chapter/character's own attribution/characterization/
     * direction/provision task appears there as it's dispatched, same Kinds
     * as the single-item buttons use), by refetching the book's speaker table
     * as chapters/characters complete, and via bookSummaryDTO.Preprocessing
     * (see isPreprocessing) for a simple whole-book "still running" indicator
     * - the library page polls this to show a spinner over the cover for as
     * long as it's true.
     *
     * Rejects (409) a second call for a book that already has one of these
     * running - see jobs.ErrPipelineAlreadyRunning.
     *
     * chapters is listed once here, before any phase is even enqueued, and
     * shared unchanged by every chapter-scoped phase below (see their own doc comments for why that
     * staleness is safe) - mirroring the one piece of shared, hoisted state
     * the old single-goroutine runBookPipeline used to keep across its own
     * four inline phases; a failure listing it aborts the whole preprocessing
     * request up front (500) rather than starting phase 1 with nothing to do.
     */
    @POST("api/books/{id}/preprocess")
    suspend fun preprocessBook(
        @Path("id") id: String,
    ): QueuedResponseDto

    /**
     * handleResetPass is POST /api/books/{id}/reset/{pass} - the Speakers
     * page's per-column reset buttons: clears one pass across the whole book as
     * though it had never run, and deletes whatever generated audio it made
     * stale. pass is a bulk action name:
     *   - "attribution"/"description"/"scare_quote"/"direction"/"pronunciation":
     *     the paragraph data that pass wrote plus its chapters.passes flag (see
     *     store.PassResets), invalidating audio for just the paragraphs whose
     *     narration it changed (and their scare-quote merge groups). The
     *     character roster is left alone - "Delete speaker data" covers that.
     *   - "music_scoring": every music region (and its clip), unsetting
     *     passes.music
     *   - "music_generation": every music region's clip, back to pending
     *   - "generate": every narration clip - handleDeleteBookAudio's action
     *
     * The paragraph passes accept ?fromChapter=<idx> to reset only chapters at
     * or after that index instead of the whole book; the other passes reject it.
     *
     * Doesn't cancel an in-flight run of the same pass, which would set its
     * flag again as it finishes - the Speakers page disables a reset while its
     * pass is running. 200 {"invalidated": n}, n = paragraphs whose audio was
     * deleted (0 for the music/generate resets).
     */
    @POST("api/books/{id}/reset/{pass}")
    suspend fun resetPass(
        @Path("id") id: String,
        @Path("pass") pass: ResetPass,
        @Query("fromChapter") fromChapter: String? = null,
    ): InvalidatedResponseDto

    @GET("api/books/{id}/search")
    suspend fun searchBook(
        @Path("id") id: String,
        @Query("q") q: String? = null,
    ): List<SearchResultDto>

    /**
     * handleListSpeakers reports every speaker recognized in bookID so far -
     * the Narrator plus every attributed character - and how much of each
     * one's audio has actually been generated, so the reader can see which
     * character voices are worth assigning/regenerating before committing to a
     * full multi-voice pass. Speaker attribution and character-voice
     * assignment work the same regardless of book.MultiVoice; this table just
     * reports what would narrate if it's on (see internal/narration.Resolver).
     */
    @GET("api/books/{id}/speakers")
    suspend fun listSpeakers(
        @Path("id") id: String,
    ): List<SpeakerDto>

    /**
     * handleDeleteBookSpeakerData clears every piece of speaker data visible
     * on book's Speakers page: this book's own paragraph attribution (back
     * to "" - Store.ClearBookSpeakers) and, for book's whole series scope
     * (store.SeriesScope - the same scope handleListSpeakers already draws
     * the roster from), every character's identity/Summary, every clone
     * model's voice assignment, and every voice preset auto-created for one
     * of them (+ its cached reference clip) - the Speakers page's own
     * "Delete speaker data" button, for starting completely over. Like
     * handleDeleteCustomVoicePreset, preset deletion here doesn't check
     * whether a preset is also referenced elsewhere (a book's own voice, the
     * default voice, another character happening to share it) first - same
     * no-safety-net convention as deleting one preset manually from the
     * Voices page, just applied in bulk. Best-effort past the first two
     * steps: one character's cleanup failing is logged and skipped rather
     * than aborting the rest, since a bulk delete partially failing and
     * leaving the reader unsure what's left is worse than "cleaned up
     * everything it could, logged what it couldn't."
     */
    @DELETE("api/books/{id}/speakers")
    suspend fun deleteBookSpeakerData(
        @Path("id") id: String,
    ): Unit

    /**
     * handleReattributeSpeaker is the "Auto Split" button's entry point: for a
     * speaker believed not to be a real, distinct individual - a false-positive
     * character attribution's own accidental character row, or the "Unknown"
     * sentinel itself, e.g. after a reader manually renamed/deleted the wrong
     * speaker upstream - it re-judges every one of that speaker's own
     * paragraphs in this book (chapter by chapter, one KindSpeakerReattribution
     * task per chapter, all grouped under one pipeline_auto_split task - see
     * jobs.Manager.EnqueueBulk/RunReattribution) and
     * redistributes them to whichever real character/Narrator/Unknown they
     * actually belong to, using the exact same chapter-wide LLM pass
     * attribution itself already runs (reattributeChapterSpeaker reuses
     * speakerattr.Client.AttributeChapter directly - no second prompt), just
     * with req.Name withheld from "Known characters" and never accepted back
     * as a result for one of its own paragraphs (see reattributeChapterSpeaker's
     * own doc comment).
     *
     * A real character (not Unknown) is marked invalid (store.Character.
     * Invalid) before anything is queued, so the name isn't recreated or
     * reassigned by this or any later attribution pass.
     *
     * Deliberately does NOT delete the character's own identity/voice
     * afterward, even if this run ends up reattributing every one of their
     * paragraphs - unlike handleDeleteCharacter/handleMergeCharacter, which are
     * one synchronous action that knows the outcome immediately, this fans out
     * into several fire-and-forget background tasks with no single moment
     * "reattribution finished" to hang that cleanup off of. A reader can always
     * follow up with the existing Delete button once they see the row is
     * actually empty.
     */
    @POST("api/books/{id}/speakers/reattribute")
    suspend fun reattributeSpeaker(
        @Path("id") id: String,
        @Body body: ReattributeSpeakerRequestDto,
    ): QueuedResponseDto

    /**
     * handleRegenerateVariant re-renders the emotion variant speaker's lines in
     * bookID clone from (whichever preset they currently generate under - see
     * narration.Resolver.ForParagraph): deletes the old take (and any failure
     * marker), resets this book's audio for that speaker's lines in that
     * emotion to pending, and queues the new render right away so it can be
     * previewed. Another book sharing the same preset keeps its already-
     * generated audio until regenerated there. 202 on success.
     */
    @POST("api/books/{id}/speakers/variants/regenerate")
    suspend fun regenerateVariant(
        @Path("id") id: String,
        @Body body: RegenerateVariantRequestDto,
    ): QueuedResponseDto

    @GET("api/books/{id}/voice")
    suspend fun getVoice(
        @Path("id") id: String,
    ): VoiceSettingsDto

    @PUT("api/books/{id}/voice")
    suspend fun updateVoice(
        @Path("id") id: String,
        @Body body: VoiceSettingsUpdateDto,
    ): VoiceSettingsDto

    @Streaming
    @GET("api/images/{id}")
    suspend fun getImage(
        @Path("id") id: String,
    ): ResponseBody

    /**
     * handleGetInstance reports this backend's stable identity (see
     * internal/instanceid) - a client caching data locally (the Android app's
     * offline downloads - see android/CLAUDE.md) uses this to scope that cache
     * per-backend, since book IDs alone are only unique within one backend.
     * Name is the optional LIBRARY_NAME operators can set purely so a client
     * juggling multiple backends has something human-readable to show, distinct
     * from id (never meant to be read by a person).
     */
    @GET("api/instance")
    suspend fun getInstance(): InstanceDto

    /**
     * handleJobsSnapshot is buildJobsSnapshot over HTTP - GET /api/jobs.
     */
    @GET("api/jobs")
    suspend fun jobsSnapshot(): JobsSnapshotDto

    /**
     * handleCancelAllJobs cancels every queued and in-flight task at once - the
     * Jobs dashboard's "Cancel all" button. See jobs.Manager.CancelAll's own
     * doc comment for what the returned count actually reflects.
     */
    @DELETE("api/jobs")
    suspend fun cancelAllJobs(): CanceledCountResponseDto

    /**
     * handlePauseJobs stops the queue from dispatching any *new* task - the
     * Jobs dashboard's "Pause" button. Whatever's already in flight keeps
     * running to completion (see jobs.Manager.Pause's own doc comment) -
     * this is not a cancel, and reverses cleanly via handleResumeJobs.
     */
    @POST("api/jobs/pause")
    suspend fun pauseJobs(): Unit

    /**
     * handleRestartWorker forces an immediate ttsworker restart - the Jobs
     * dashboard's "Restart ttsworker" button, for recovering a stuck or
     * visibly-leaking worker (see ttsworker.Manager's own RSS-threshold
     * watchdog for the automatic version of this) without waiting for a
     * crash or the RSS threshold to be crossed on its own. Blocks until the
     * new worker is confirmed healthy (ttsworker.Manager.Restart's own
     * restartGate already blocks every other in-flight TTS/LLM call for the
     * same duration), then reports success/failure directly rather than
     * firing-and-forgetting it - a restart is rare and worth the reader
     * actually seeing whether it worked.
     */
    @POST("api/jobs/restart-worker")
    suspend fun restartWorker(): Unit

    /**
     * handleResumeJobs undoes handlePauseJobs.
     */
    @POST("api/jobs/resume")
    suspend fun resumeJobs(): Unit

    /**
     * handleCancelJob cancels one job-queue task by its id (queueTaskDTO.ID,
     * i.e. jobs.QueueTask.ID) - the Jobs dashboard's per-row "Cancel" button.
     * 404 if id doesn't match anything currently queued or in flight (already
     * finished on its own, or never existed) - see jobs.Manager.Cancel's own
     * doc comment for exactly what "cancel" means for a queued vs. in-flight
     * task.
     */
    @DELETE("api/jobs/{id}")
    suspend fun cancelJob(
        @Path("id") id: String,
    ): Unit

    /**
     * handleSetJobTier raises one job-queue task's own priority tier - the
     * Jobs dashboard's per-row priority menu (click a row's Tier badge, pick
     * something more urgent). See jobs.Manager.PromoteTier's own doc comment
     * for why this can only ever raise urgency, never lower it: 409 if the
     * requested tier isn't strictly more urgent than the task's current one
     * (e.g. re-requesting the tier it's already at, or something already more
     * urgent), 404 if id doesn't match anything currently queued or in
     * flight, 400 for a malformed body or an unrecognized tier string.
     */
    @PUT("api/jobs/{id}/tier")
    suspend fun setJobTier(
        @Path("id") id: String,
        @Body body: JobTierRequestDto,
    ): Unit

    /**
     * handleTestLLM is a standalone raw-prompt test surface for this app's
     * own embedded speaker-attribution GGUF model (internal/llmworker,
     * proxied through ttsworker.Manager.LLMGenerate) - stateless, not tied to
     * any book/chapter, for exercising a system+user prompt pair directly
     * (e.g. iterating on a speakerattr-style prompt) without running a real
     * attribution/characterization/direction-tagging pass.
     *
     * Dispatched through jobs.Manager.RunLLMPreview (KindLLMPreview, poolLLM)
     * rather than calling s.TTS.LLMGenerate directly - same "handled as a
     * pooled job" reasoning handleGenerateSFX's own doc comment gives:
     * llmworker already serves concurrent calls natively via multi-sequence
     * batching (llamacpp.Scheduler - see backend/CLAUDE.md's "ttsworker /
     * audioworker / llmworker" section), so this doesn't buy GPU-residency
     * mutual exclusion the way poolSFX does, but it does get this call
     * TierUrgent priority over queued background attribution/
     * characterization/direction-tagging work and visibility on the Jobs
     * dashboard, same as every other test surface in this package.
     */
    @POST("api/llm/test")
    suspend fun testLLM(
        @Body body: TestLLMRequestDto,
    ): LlmTestResponseDto

    /**
     * handleGetMusicRegionAudio serves GET /api/music-regions/{id}/audio - the
     * frontend's own background-music mixer fetches each region's clip by this
     * URL (musicRegionDTO.AudioURL) as narration crosses into its paragraph
     * range. Range-request-capable via http.ServeFile, same as
     * handleGetAudio/handleGetParagraphSFXAudio.
     */
    @Streaming
    @GET("api/music-regions/{id}/audio")
    suspend fun getMusicRegionAudio(
        @Path("id") id: String,
    ): ResponseBody

    /**
     * handleRegenerateMusicRegion is POST /api/music-regions/{id}/regenerate -
     * the reader's own per-region "Generate"/"Regenerate" button in
     * annotations view (ChapterSection.MusicRegionBoundary), for a region
     * that's either never been generated yet (still AudioPending, or
     * AudioError from an earlier failed attempt) or one whose already-ready
     * clip the reader just wants re-rolled. Always allowed regardless of
     * current status - store.Store.ResetMusicRegionAudio's own doc comment
     * covers why resetting an already-pending region is harmless.
     *
     * Deletes the old on-disk clip first (best-effort - a region that was
     * never generated has none to remove), then re-dispatches through the
     * same jobs.Manager.MaybeAdvanceChapterMusic path narration completion
     * already uses, and immediately promotes the freshly (re-)queued
     * generation task to TierUrgent - an explicit reader click deserves the
     * same "don't wait behind unrelated background work" treatment
     * EnqueueParagraphRegenerate's own TierUrgent already gives narration.
     * Generation dispatches as one batch task per chapter, not per region (see
     * jobs.Manager.EnqueueMusicGeneration's own doc comment), so promoting
     * "music_gen:"+chapterID by jobs.Manager.PromoteTier directly already
     * covers this region along with whatever else in the chapter is eligible
     * to generate alongside it - there's no narrower per-region task id left
     * to promote instead.
     *
     * Known imperfection: doesn't cascade-invalidate a *following*
     * MusicTransitionContinuation region that was already generated seeded
     * from this region's own (about-to-change) clip - that region's own
     * already-ready audio just keeps playing, now seeded from audio that no
     * longer matches. Regenerating that one too, if the mismatch is audible,
     * is a second manual click away; not worth chasing automatically for a
     * first version of this button.
     */
    @POST("api/music-regions/{id}/regenerate")
    suspend fun regenerateMusicRegion(
        @Path("id") id: String,
    ): QueuedResponseDto

    @Streaming
    @GET("api/paragraphs/{id}/audio")
    suspend fun getAudio(
        @Path("id") id: String,
    ): ResponseBody

    /**
     * handleGetParagraphSFXAudio serves a ready sound-effect clip -
     * handleGetAudio's own counterpart, simpler since SFX audio isn't
     * voice-scoped.
     */
    @Streaming
    @GET("api/paragraphs/{id}/sfx-audio")
    suspend fun getParagraphSFXAudio(
        @Path("id") id: String,
    ): ResponseBody

    /**
     * handleGenerateSFX is the standalone SFX/music test page's own backend
     * surface (see frontend SFXPage.tsx) - handleTestVoiceDesign's own
     * counterpart for this app's generation-only engines: stateless, not
     * attached to any book/chapter/paragraph, returns raw WAV bytes rather
     * than persisting anything. A paragraph wanting to keep a generated
     * sound-effect clip uses the paragraph-scoped POST .../generate-sfx
     * endpoint instead (handleGenerateParagraphSFX, chapters.go) - this one is
     * purely for iterating on a prompt/knob/engine combination before (or
     * without) attaching one to a real paragraph.
     *
     * Dispatched through jobs.Manager.RunSFXPreview (KindSFXPreview, poolSFX)
     * rather than calling s.TTS directly - same "handled as a pooled job"
     * reasoning handleGenerateParagraphSFX's own doc comment gives: this way a
     * standalone test render properly queues/shares poolSFX's own concurrency
     * limit and TTS/LLM-pool mutual exclusion with every other real
     * generation task, instead of racing the worker uncoordinated. One
     * endpoint for every engine, not one per engine: RunSFXPreview doesn't
     * care which of them a given call's own closure actually invokes.
     */
    @Streaming
    @POST("api/sfx/generate")
    suspend fun generateSFX(
        @Body body: GenerateSFXRequestDto,
    ): ResponseBody

    /**
     * handleTestCloneInstruct previews "instructed voice cloning" -
     * breeze_tts's own ability to clone a reference clip *and* apply a style
     * instruction in one call - given an existing voice to clone the reference
     * clip from (BaseID) and a free-form instruction to style it with, without
     * saving anything as a preset first. Backs the voice/character editor's
     * "test with another voice as a base" control - the same thing a reader
     * would use to preview what store.Book.InstructCharacterVoices actually
     * sounds like for one character before turning it on for a whole book.
     */
    @Streaming
    @POST("api/voices/clone-instruct-test")
    suspend fun testCloneInstruct(
        @Body body: TestCloneInstructRequestDto,
    ): ResponseBody

    @GET("api/voices/custom-presets")
    suspend fun listCustomVoicePresets(): List<CustomVoicePresetDto>

    @POST("api/voices/custom-presets")
    suspend fun createCustomVoicePreset(
        @Body body: CustomVoicePresetInputDto,
    ): CustomVoicePresetDto

    @PUT("api/voices/custom-presets/{id}")
    suspend fun updateCustomVoicePreset(
        @Path("id") id: String,
        @Body body: CustomVoicePresetInputDto,
    ): CustomVoicePresetDto

    @DELETE("api/voices/custom-presets/{id}")
    suspend fun deleteCustomVoicePreset(
        @Path("id") id: String,
    ): Unit

    /**
     * handleGetCustomVoiceAudio serves a custom preset's reference clip -
     * what the user will actually hear as their narrator, previewable the
     * same way as a built-in one. Created on first request if it's missing
     * (e.g. the worker was unavailable when this preset was created/edited).
     */
    @Streaming
    @GET("api/voices/custom-presets/{id}/audio")
    suspend fun getCustomVoiceAudio(
        @Path("id") id: String,
    ): ResponseBody

    /**
     * handleRegenerateCustomVoicePreset force re-renders id's reference clip
     * via VoiceDesign from its currently-saved recipe, without touching any of
     * the preset's saved fields - the "Regenerate" button on the Voices page,
     * for retrying after a RefError (tts-service was briefly down, e.g.) or
     * just to pick up a fresh render, without going through Edit -> Save
     * unchanged to get the same effect (see handleUpdateCustomVoicePreset,
     * which always regenerates too, but only as a side effect of saving).
     *
     * Routed through jobs.Manager.RunVoiceProvision (a KindVoiceProvision
     * task, dedup key "regenerate:"+p.ID) rather than calling voicerefs.
     * Regenerate directly, so this shows up on the Jobs dashboard like any
     * other voice work and queues behind - never races - a characterization
     * task for the same identity (see taskBlockedBySpeakerCharacterization);
     * still blocks this handler's own response the same way the direct call
     * used to, so the response shape (voicePresetDTO, synchronous refErr)
     * is unchanged for the frontend.
     *
     * A successful re-render invalidates every already-generated paragraph
     * that was cloned from the old clip: the recipe (instruct/seed/refText)
     * is unchanged by this action, so paragraph_audio's own voice_id (a hash
     * of presetID+instruct+language, not of the clip's actual audio content -
     * see store.VoiceID) never changes and wouldn't otherwise orphan anything,
     * even though the underlying reference audio genuinely did just change -
     * see invalidateAudioForVoicePreset.
     */
    @POST("api/voices/custom-presets/{id}/regenerate")
    suspend fun regenerateCustomVoicePreset(
        @Path("id") id: String,
    ): CustomVoicePresetDto

    /**
     * handleTestCustomVoicePreset synthesizes arbitrary text with an existing
     * custom preset's actual saved voice (its real clone, same path as book
     * narration - not a one-off design-path guess), so the editor can hear how
     * it sounds on something other than the fixed reference line before using
     * it in a book.
     */
    @Streaming
    @POST("api/voices/custom-presets/{id}/test")
    suspend fun testCustomVoicePreset(
        @Path("id") id: String,
        @Body body: TestVoiceRequestDto,
    ): ResponseBody

    /**
     * handleGetDefaultVoice reports the voice new books are created with.
     */
    @GET("api/voices/default")
    suspend fun getDefaultVoice(): VoiceSettingsDto

    /**
     * handleUpdateDefaultVoice sets the voice and clone model new books are
     * created with - "selecting" a voice (or picking the default clone model)
     * on the Voices page. Existing books are unaffected; this only changes
     * what a freshly uploaded book starts with.
     */
    @PUT("api/voices/default")
    suspend fun updateDefaultVoice(
        @Body body: VoiceSettingsUpdateDto,
    ): VoiceSettingsDto

    /**
     * handleTestVoiceDesign previews a voice instruction directly via the
     * worker's stateless VoiceDesign task (no preset_id at all, unlike
     * handleTestCustomVoicePreset/handleTestPreset, which both require one) -
     * the only way to hear an instruct before it's been saved as a preset.
     * When Seed is given, the render is also cached by its exact (instruct,
     * seed, text, language) recipe (see voicerefs.DesignConfigHash) so that
     * creating the preset right after testing it, unchanged, reuses this exact
     * clip instead of paying for a second render.
     *
     * Runs through jobs.Manager.RunVoiceDesignPreview (a real
     * KindVoiceDesignPreview task in poolGeneration) rather than calling
     * s.TTS.Design directly - this used to bypass the job queue entirely, so a
     * "Test" click competed for the ttsworker process uncoordinated with (and
     * outside the concurrency limit protecting) actual paragraph generation.
     * Still blocks and returns the WAV bytes inline, same as before - see
     * RunVoiceDesignPreview's own doc comment for why that shape is kept.
     */
    @Streaming
    @POST("api/voices/design-test")
    suspend fun testVoiceDesign(
        @Body body: TestVoiceDesignRequestDto,
    ): ResponseBody

    @GET("api/voices/languages")
    suspend fun voiceLanguages(): LanguagesResponseDto

    @GET("api/voices/presets")
    suspend fun voicePresets(): VoicePresetsDto

    /**
     * handleGetPresetAudio serves a built-in preset's reference clip, so the
     * user can preview what a curated narrator actually sounds like before
     * picking it. Created on first request if the worker hasn't rendered one
     * yet (e.g. this preset has never been used).
     */
    @Streaming
    @GET("api/voices/presets/{id}/audio")
    suspend fun getPresetAudio(
        @Path("id") id: String,
    ): ResponseBody

    /**
     * handleRegeneratePreset is the built-in-preset equivalent of
     * handleRegenerateCustomVoicePreset - force re-renders id's reference clip
     * via VoiceDesign from its fixed, compiled-in recipe (built-ins are never
     * stored in the DB - see internal/voices' own doc comment - but their
     * rendered reference clip is cached on disk under their own id exactly
     * like a custom preset's, via the same internal/voicerefs). Useful to
     * retry after tts-service was briefly down when a preset's clip was first
     * needed, without waiting for the next arbitrary request that happens to
     * call EnsureFile on it.
     */
    @POST("api/voices/presets/{id}/regenerate")
    suspend fun regeneratePreset(
        @Path("id") id: String,
    ): VoicePresetDto

    /**
     * handleTestPreset is the built-in-preset equivalent of
     * handleTestCustomVoicePreset, so the same "hear it on other text" preview
     * works for curated presets too, not just custom ones.
     */
    @Streaming
    @POST("api/voices/presets/{id}/test")
    suspend fun testPreset(
        @Path("id") id: String,
        @Body body: TestVoiceRequestDto,
    ): ResponseBody

    /**
     * handleVariantAudio serves one emotion variant of a voice preset's
     * reference clip (see voicerefs.EnsureVariantFile) - the Speakers page's
     * per-emotion preview. 404 until it's been rendered.
     */
    @Streaming
    @GET("api/voices/variants/{presetId}/{emotion}/audio")
    suspend fun variantAudio(
        @Path("presetId") presetId: String,
        @Path("emotion") emotion: String,
    ): ResponseBody
}
