// Code generated by backend/cmd/apigen from backend/internal/httpapi. DO NOT EDIT.

@file:Suppress("unused")

package com.lectable.app.data.remote

import com.lectable.app.data.remote.dto.*
import kotlinx.serialization.KSerializer
import kotlinx.serialization.serializer

/**
 * One live topic instance (GET /api/events): its wire name, params, and how to decode its value.
 */
class LiveTopic<T>(val name: String, val params: Map<String, Any>, val deserializer: KSerializer<T>)

/**
 * Every live topic the backend serves.
 */
object LiveTopics {
    fun books(): LiveTopic<List<BookSummaryDto>> =
        LiveTopic("books", emptyMap(), serializer<List<BookSummaryDto>>())

    fun book(bookId: String): LiveTopic<BookDetailDto> =
        LiveTopic("book", mapOf("bookId" to bookId), serializer<BookDetailDto>())

    fun chapter(bookId: String, chapterIdx: Int): LiveTopic<ChapterDetailDto> =
        LiveTopic("chapter", mapOf("bookId" to bookId, "chapterIdx" to chapterIdx), serializer<ChapterDetailDto>())

    fun chapterMusic(bookId: String, chapterIdx: Int): LiveTopic<ChapterMusicDto> =
        LiveTopic("chapterMusic", mapOf("bookId" to bookId, "chapterIdx" to chapterIdx), serializer<ChapterMusicDto>())

    fun voice(bookId: String): LiveTopic<VoiceSettingsDto> =
        LiveTopic("voice", mapOf("bookId" to bookId), serializer<VoiceSettingsDto>())

    fun speakers(bookId: String): LiveTopic<List<SpeakerDto>> =
        LiveTopic("speakers", mapOf("bookId" to bookId), serializer<List<SpeakerDto>>())

    fun characterAppearances(bookId: String, characterId: String): LiveTopic<List<SpeakerAppearanceDto>> =
        LiveTopic("characterAppearances", mapOf("bookId" to bookId, "characterId" to characterId), serializer<List<SpeakerAppearanceDto>>())

    fun characterDescriptions(bookId: String, characterId: String): LiveTopic<List<SpeakerAppearanceDto>> =
        LiveTopic("characterDescriptions", mapOf("bookId" to bookId, "characterId" to characterId), serializer<List<SpeakerAppearanceDto>>())

    fun bookmarks(bookId: String): LiveTopic<List<BookmarkDto>> =
        LiveTopic("bookmarks", mapOf("bookId" to bookId), serializer<List<BookmarkDto>>())

    fun bookExports(bookId: String): LiveTopic<List<BookExportDto>> =
        LiveTopic("bookExports", mapOf("bookId" to bookId), serializer<List<BookExportDto>>())

    fun jobs(): LiveTopic<JobsSnapshotDto> =
        LiveTopic("jobs", emptyMap(), serializer<JobsSnapshotDto>())

    fun voicePresets(): LiveTopic<VoicePresetsDto> =
        LiveTopic("voicePresets", emptyMap(), serializer<VoicePresetsDto>())

    fun customVoicePresets(): LiveTopic<List<CustomVoicePresetDto>> =
        LiveTopic("customVoicePresets", emptyMap(), serializer<List<CustomVoicePresetDto>>())

    fun defaultVoice(): LiveTopic<VoiceSettingsDto> =
        LiveTopic("defaultVoice", emptyMap(), serializer<VoiceSettingsDto>())
}
